package dtos

type CreateMetadata struct {
	Name string `json:"name"`
	Metadata []*Metadata `json:"metadata,omitempty"`
}

type CreateMetadataResponse struct {
	Result []*SaveResult `json:"result,omitempty"`
}

type SaveResult struct {
	Errors []*Error `json:"errors,omitempty"`

	FullName string `json:"fullName,omitempty"`

	Success bool `json:"success,omitempty"`
}

type Error struct {
	ExtendedErrorDetails []*ExtendedErrorDetails `json:"extendedErrorDetails,omitempty"`

	Fields []string `json:"fields,omitempty"`

	Message string `json:"message,omitempty"`

	StatusCode *StatusCode `json:"statusCode,omitempty"`
}

type ExtendedErrorDetails struct {
	ExtendedErrorCode *ExtendedErrorCode `json:"extendedErrorCode,omitempty"`
}

type ExtendedErrorCode string

type StatusCode string

const (
	StatusCodeALLORNONEOPERATIONROLLEDBACK StatusCode = "ALLORNONEOPERATIONROLLEDBACK"

	StatusCodeALREADYINPROCESS StatusCode = "ALREADYINPROCESS"

	StatusCodeAPEXDATAACCESSRESTRICTION StatusCode = "APEXDATAACCESSRESTRICTION"

	StatusCodeASSIGNEETYPEREQUIRED StatusCode = "ASSIGNEETYPEREQUIRED"

	StatusCodeAURACOMPILEERROR StatusCode = "AURACOMPILEERROR"

	StatusCodeBADCUSTOMENTITYPARENTDOMAIN StatusCode = "BADCUSTOMENTITYPARENTDOMAIN"

	StatusCodeBCCNOTALLOWEDIFBCCCOMPLIANCEENABLED StatusCode = "BCCNOTALLOWEDIFBCCCOMPLIANCEENABLED"

	StatusCodeCANNOTCASCADEPRODUCTACTIVE StatusCode = "CANNOTCASCADEPRODUCTACTIVE"

	StatusCodeCANNOTCHANGEFIELDTYPEOFAPEXREFERENCEDFIELD StatusCode = "CANNOTCHANGEFIELDTYPEOFAPEXREFERENCEDFIELD"

	StatusCodeCANNOTCHANGEFIELDTYPEOFREFERENCEDFIELD StatusCode = "CANNOTCHANGEFIELDTYPEOFREFERENCEDFIELD"

	StatusCodeCANNOTCREATEANOTHERMANAGEDPACKAGE StatusCode = "CANNOTCREATEANOTHERMANAGEDPACKAGE"

	StatusCodeCANNOTDEACTIVATEDIVISION StatusCode = "CANNOTDEACTIVATEDIVISION"

	StatusCodeCANNOTDELETEGLOBALACTIONLIST StatusCode = "CANNOTDELETEGLOBALACTIONLIST"

	StatusCodeCANNOTDELETELASTDATEDCONVERSIONRATE StatusCode = "CANNOTDELETELASTDATEDCONVERSIONRATE"

	StatusCodeCANNOTDELETEMANAGEDOBJECT StatusCode = "CANNOTDELETEMANAGEDOBJECT"

	StatusCodeCANNOTDISABLELASTADMIN StatusCode = "CANNOTDISABLELASTADMIN"

	StatusCodeCANNOTENABLEIPRESTRICTREQUESTS StatusCode = "CANNOTENABLEIPRESTRICTREQUESTS"

	StatusCodeCANNOTEXECUTEFLOWTRIGGER StatusCode = "CANNOTEXECUTEFLOWTRIGGER"

	StatusCodeCANNOTFREEZESELF StatusCode = "CANNOTFREEZESELF"

	StatusCodeCANNOTINSERTUPDATEACTIVATEENTITY StatusCode = "CANNOTINSERTUPDATEACTIVATEENTITY"

	StatusCodeCANNOTMODIFYMANAGEDOBJECT StatusCode = "CANNOTMODIFYMANAGEDOBJECT"

	StatusCodeCANNOTPASSWORDLOCKOUT StatusCode = "CANNOTPASSWORDLOCKOUT"

	StatusCodeCANNOTPOSTTOARCHIVEDGROUP StatusCode = "CANNOTPOSTTOARCHIVEDGROUP"

	StatusCodeCANNOTRENAMEAPEXREFERENCEDFIELD StatusCode = "CANNOTRENAMEAPEXREFERENCEDFIELD"

	StatusCodeCANNOTRENAMEAPEXREFERENCEDOBJECT StatusCode = "CANNOTRENAMEAPEXREFERENCEDOBJECT"

	StatusCodeCANNOTRENAMEREFERENCEDFIELD StatusCode = "CANNOTRENAMEREFERENCEDFIELD"

	StatusCodeCANNOTRENAMEREFERENCEDOBJECT StatusCode = "CANNOTRENAMEREFERENCEDOBJECT"

	StatusCodeCANNOTREPARENTRECORD StatusCode = "CANNOTREPARENTRECORD"

	StatusCodeCANNOTUPDATECONVERTEDLEAD StatusCode = "CANNOTUPDATECONVERTEDLEAD"

	StatusCodeCANTDISABLECORPCURRENCY StatusCode = "CANTDISABLECORPCURRENCY"

	StatusCodeCANTUNSETCORPCURRENCY StatusCode = "CANTUNSETCORPCURRENCY"

	StatusCodeCHILDSHAREFAILSPARENT StatusCode = "CHILDSHAREFAILSPARENT"

	StatusCodeCIRCULARDEPENDENCY StatusCode = "CIRCULARDEPENDENCY"

	StatusCodeCLEANSERVICEERROR StatusCode = "CLEANSERVICEERROR"

	StatusCodeCOLLISIONDETECTED StatusCode = "COLLISIONDETECTED"

	StatusCodeCOMMUNITYNOTACCESSIBLE StatusCode = "COMMUNITYNOTACCESSIBLE"

	StatusCodeCONFLICTINGENVIRONMENTHUBMEMBER StatusCode = "CONFLICTINGENVIRONMENTHUBMEMBER"

	StatusCodeCONFLICTINGSSOUSERMAPPING StatusCode = "CONFLICTINGSSOUSERMAPPING"

	StatusCodeCUSTOMAPEXERROR StatusCode = "CUSTOMAPEXERROR"

	StatusCodeCUSTOMCLOBFIELDLIMITEXCEEDED StatusCode = "CUSTOMCLOBFIELDLIMITEXCEEDED"

	StatusCodeCUSTOMENTITYORFIELDLIMIT StatusCode = "CUSTOMENTITYORFIELDLIMIT"

	StatusCodeCUSTOMFIELDINDEXLIMITEXCEEDED StatusCode = "CUSTOMFIELDINDEXLIMITEXCEEDED"

	StatusCodeCUSTOMINDEXEXISTS StatusCode = "CUSTOMINDEXEXISTS"

	StatusCodeCUSTOMLINKLIMITEXCEEDED StatusCode = "CUSTOMLINKLIMITEXCEEDED"

	StatusCodeCUSTOMMETADATALIMITEXCEEDED StatusCode = "CUSTOMMETADATALIMITEXCEEDED"

	StatusCodeCUSTOMSETTINGSLIMITEXCEEDED StatusCode = "CUSTOMSETTINGSLIMITEXCEEDED"

	StatusCodeCUSTOMTABLIMITEXCEEDED StatusCode = "CUSTOMTABLIMITEXCEEDED"

	StatusCodeDATACLOUDADDRESSNORECORDSFOUND StatusCode = "DATACLOUDADDRESSNORECORDSFOUND"

	StatusCodeDATACLOUDADDRESSPROCESSINGERROR StatusCode = "DATACLOUDADDRESSPROCESSINGERROR"

	StatusCodeDATACLOUDADDRESSSERVERERROR StatusCode = "DATACLOUDADDRESSSERVERERROR"

	StatusCodeDELETEFAILED StatusCode = "DELETEFAILED"

	StatusCodeDELETEOPERATIONTOOLARGE StatusCode = "DELETEOPERATIONTOOLARGE"

	StatusCodeDELETEREQUIREDONCASCADE StatusCode = "DELETEREQUIREDONCASCADE"

	StatusCodeDEPENDENCYEXISTS StatusCode = "DEPENDENCYEXISTS"

	StatusCodeDUPLICATESDETECTED StatusCode = "DUPLICATESDETECTED"

	StatusCodeDUPLICATECASESOLUTION StatusCode = "DUPLICATECASESOLUTION"

	StatusCodeDUPLICATECOMMNICKNAME StatusCode = "DUPLICATECOMMNICKNAME"

	StatusCodeDUPLICATECUSTOMENTITYDEFINITION StatusCode = "DUPLICATECUSTOMENTITYDEFINITION"

	StatusCodeDUPLICATECUSTOMTABMOTIF StatusCode = "DUPLICATECUSTOMTABMOTIF"

	StatusCodeDUPLICATEDEVELOPERNAME StatusCode = "DUPLICATEDEVELOPERNAME"

	StatusCodeDUPLICATEEXTERNALID StatusCode = "DUPLICATEEXTERNALID"

	StatusCodeDUPLICATEMASTERLABEL StatusCode = "DUPLICATEMASTERLABEL"

	StatusCodeDUPLICATESENDERDISPLAYNAME StatusCode = "DUPLICATESENDERDISPLAYNAME"

	StatusCodeDUPLICATEUSERNAME StatusCode = "DUPLICATEUSERNAME"

	StatusCodeDUPLICATEVALUE StatusCode = "DUPLICATEVALUE"

	StatusCodeEMAILADDRESSBOUNCED StatusCode = "EMAILADDRESSBOUNCED"

	StatusCodeEMAILEXTERNALTRANSPORTCONNECTIONERROR StatusCode = "EMAILEXTERNALTRANSPORTCONNECTIONERROR"

	StatusCodeEMAILEXTERNALTRANSPORTTOKENERROR StatusCode = "EMAILEXTERNALTRANSPORTTOKENERROR"

	StatusCodeEMAILEXTERNALTRANSPORTTOOMANYREQUESTSERROR StatusCode = "EMAILEXTERNALTRANSPORTTOOMANYREQUESTSERROR"

	StatusCodeEMAILEXTERNALTRANSPORTUNKNOWNERROR StatusCode = "EMAILEXTERNALTRANSPORTUNKNOWNERROR"

	StatusCodeEMAILNOTPROCESSEDDUETOPRIORERROR StatusCode = "EMAILNOTPROCESSEDDUETOPRIORERROR"

	StatusCodeEMAILOPTEDOUT StatusCode = "EMAILOPTEDOUT"

	StatusCodeEMAILTEMPLATEFORMULAERROR StatusCode = "EMAILTEMPLATEFORMULAERROR"

	StatusCodeEMAILTEMPLATEMERGEFIELDACCESSERROR StatusCode = "EMAILTEMPLATEMERGEFIELDACCESSERROR"

	StatusCodeEMAILTEMPLATEMERGEFIELDERROR StatusCode = "EMAILTEMPLATEMERGEFIELDERROR"

	StatusCodeEMAILTEMPLATEMERGEFIELDVALUEERROR StatusCode = "EMAILTEMPLATEMERGEFIELDVALUEERROR"

	StatusCodeEMAILTEMPLATEPROCESSINGERROR StatusCode = "EMAILTEMPLATEPROCESSINGERROR"

	StatusCodeEMPTYSCONTROLFILENAME StatusCode = "EMPTYSCONTROLFILENAME"

	StatusCodeENTITYFAILEDIFLASTMODIFIEDONUPDATE StatusCode = "ENTITYFAILEDIFLASTMODIFIEDONUPDATE"

	StatusCodeENTITYISARCHIVED StatusCode = "ENTITYISARCHIVED"

	StatusCodeENTITYISDELETED StatusCode = "ENTITYISDELETED"

	StatusCodeENTITYISLOCKED StatusCode = "ENTITYISLOCKED"

	StatusCodeENTITYSAVEERROR StatusCode = "ENTITYSAVEERROR"

	StatusCodeENTITYSAVEVALIDATIONERROR StatusCode = "ENTITYSAVEVALIDATIONERROR"

	StatusCodeENVIRONMENTHUBMEMBERSHIPCONFLICT StatusCode = "ENVIRONMENTHUBMEMBERSHIPCONFLICT"

	StatusCodeENVIRONMENTHUBMEMBERSHIPERRORJOININGHUB StatusCode = "ENVIRONMENTHUBMEMBERSHIPERRORJOININGHUB"

	StatusCodeENVIRONMENTHUBMEMBERSHIPUSERALREADYINHUB StatusCode = "ENVIRONMENTHUBMEMBERSHIPUSERALREADYINHUB"

	StatusCodeENVIRONMENTHUBMEMBERSHIPUSERNOTORGADMIN StatusCode = "ENVIRONMENTHUBMEMBERSHIPUSERNOTORGADMIN"

	StatusCodeERRORINMAILER StatusCode = "ERRORINMAILER"

	StatusCodeEXCHANGEWEBSERVICESURLINVALID StatusCode = "EXCHANGEWEBSERVICESURLINVALID"

	StatusCodeFAILEDACTIVATION StatusCode = "FAILEDACTIVATION"

	StatusCodeFIELDCUSTOMVALIDATIONEXCEPTION StatusCode = "FIELDCUSTOMVALIDATIONEXCEPTION"

	StatusCodeFIELDFILTERVALIDATIONEXCEPTION StatusCode = "FIELDFILTERVALIDATIONEXCEPTION"

	StatusCodeFIELDINTEGRITYEXCEPTION StatusCode = "FIELDINTEGRITYEXCEPTION"

	StatusCodeFIELDKEYWORDLISTMATCHLIMIT StatusCode = "FIELDKEYWORDLISTMATCHLIMIT"

	StatusCodeFIELDMAPPINGERROR StatusCode = "FIELDMAPPINGERROR"

	StatusCodeFIELDMODERATIONRULEBLOCK StatusCode = "FIELDMODERATIONRULEBLOCK"

	StatusCodeFIELDNOTUPDATABLE StatusCode = "FIELDNOTUPDATABLE"

	StatusCodeFILEEXTENSIONNOTALLOWED StatusCode = "FILEEXTENSIONNOTALLOWED"

	StatusCodeFILESIZELIMITEXCEEDED StatusCode = "FILESIZELIMITEXCEEDED"

	StatusCodeFILTEREDLOOKUPLIMITEXCEEDED StatusCode = "FILTEREDLOOKUPLIMITEXCEEDED"

	StatusCodeFINDDUPLICATESERROR StatusCode = "FINDDUPLICATESERROR"

	StatusCodeFUNCTIONALITYNOTENABLED StatusCode = "FUNCTIONALITYNOTENABLED"

	StatusCodeHASPUBLICREFERENCES StatusCode = "HASPUBLICREFERENCES"

	StatusCodeHTMLFILEUPLOADNOTALLOWED StatusCode = "HTMLFILEUPLOADNOTALLOWED"

	StatusCodeIMAGETOOLARGE StatusCode = "IMAGETOOLARGE"

	StatusCodeINACTIVEOWNERORUSER StatusCode = "INACTIVEOWNERORUSER"

	StatusCodeINACTIVERULEERROR StatusCode = "INACTIVERULEERROR"

	StatusCodeINSERTUPDATEDELETENOTALLOWEDDURINGMAINTENANCE StatusCode = "INSERTUPDATEDELETENOTALLOWEDDURINGMAINTENANCE"

	StatusCodeINSUFFICIENTACCESSONCROSSREFERENCEENTITY StatusCode = "INSUFFICIENTACCESSONCROSSREFERENCEENTITY"

	StatusCodeINSUFFICIENTACCESSORREADONLY StatusCode = "INSUFFICIENTACCESSORREADONLY"

	StatusCodeINSUFFICIENTACCESSTOINSIGHTSEXTERNALDATA StatusCode = "INSUFFICIENTACCESSTOINSIGHTSEXTERNALDATA"

	StatusCodeINSUFFICIENTCREDITS StatusCode = "INSUFFICIENTCREDITS"

	StatusCodeINVALIDACCESSLEVEL StatusCode = "INVALIDACCESSLEVEL"

	StatusCodeINVALIDARGUMENTTYPE StatusCode = "INVALIDARGUMENTTYPE"

	StatusCodeINVALIDASSIGNEETYPE StatusCode = "INVALIDASSIGNEETYPE"

	StatusCodeINVALIDASSIGNMENTRULE StatusCode = "INVALIDASSIGNMENTRULE"

	StatusCodeINVALIDBATCHOPERATION StatusCode = "INVALIDBATCHOPERATION"

	StatusCodeINVALIDCONTENTTYPE StatusCode = "INVALIDCONTENTTYPE"

	StatusCodeINVALIDCREDITCARDINFO StatusCode = "INVALIDCREDITCARDINFO"

	StatusCodeINVALIDCROSSREFERENCEKEY StatusCode = "INVALIDCROSSREFERENCEKEY"

	StatusCodeINVALIDCROSSREFERENCETYPEFORFIELD StatusCode = "INVALIDCROSSREFERENCETYPEFORFIELD"

	StatusCodeINVALIDCURRENCYCONVRATE StatusCode = "INVALIDCURRENCYCONVRATE"

	StatusCodeINVALIDCURRENCYCORPRATE StatusCode = "INVALIDCURRENCYCORPRATE"

	StatusCodeINVALIDCURRENCYISO StatusCode = "INVALIDCURRENCYISO"

	StatusCodeINVALIDDATACATEGORYGROUPREFERENCE StatusCode = "INVALIDDATACATEGORYGROUPREFERENCE"

	StatusCodeINVALIDDATAURI StatusCode = "INVALIDDATAURI"

	StatusCodeINVALIDEMAILADDRESS StatusCode = "INVALIDEMAILADDRESS"

	StatusCodeINVALIDEMPTYKEYOWNER StatusCode = "INVALIDEMPTYKEYOWNER"

	StatusCodeINVALIDENTITYFORMATCHENGINEERROR StatusCode = "INVALIDENTITYFORMATCHENGINEERROR"

	StatusCodeINVALIDENTITYFORMATCHOPERATIONERROR StatusCode = "INVALIDENTITYFORMATCHOPERATIONERROR"

	StatusCodeINVALIDENTITYFORUPSERT StatusCode = "INVALIDENTITYFORUPSERT"

	StatusCodeINVALIDENVIRONMENTHUBMEMBER StatusCode = "INVALIDENVIRONMENTHUBMEMBER"

	StatusCodeINVALIDEVENTDELIVERY StatusCode = "INVALIDEVENTDELIVERY"

	StatusCodeINVALIDEVENTSUBSCRIPTION StatusCode = "INVALIDEVENTSUBSCRIPTION"

	StatusCodeINVALIDFIELD StatusCode = "INVALIDFIELD"

	StatusCodeINVALIDFIELDFORINSERTUPDATE StatusCode = "INVALIDFIELDFORINSERTUPDATE"

	StatusCodeINVALIDFIELDWHENUSINGTEMPLATE StatusCode = "INVALIDFIELDWHENUSINGTEMPLATE"

	StatusCodeINVALIDFILTERACTION StatusCode = "INVALIDFILTERACTION"

	StatusCodeINVALIDGOOGLEDOCSURL StatusCode = "INVALIDGOOGLEDOCSURL"

	StatusCodeINVALIDIDFIELD StatusCode = "INVALIDIDFIELD"

	StatusCodeINVALIDINETADDRESS StatusCode = "INVALIDINETADDRESS"

	StatusCodeINVALIDINPUT StatusCode = "INVALIDINPUT"

	StatusCodeINVALIDLINEITEMCLONESTATE StatusCode = "INVALIDLINEITEMCLONESTATE"

	StatusCodeINVALIDMARKUP StatusCode = "INVALIDMARKUP"

	StatusCodeINVALIDMASTERORTRANSLATEDSOLUTION StatusCode = "INVALIDMASTERORTRANSLATEDSOLUTION"

	StatusCodeINVALIDMESSAGEIDREFERENCE StatusCode = "INVALIDMESSAGEIDREFERENCE"

	StatusCodeINVALIDNAMESPACEPREFIX StatusCode = "INVALIDNAMESPACEPREFIX"

	StatusCodeINVALIDOAUTHURL StatusCode = "INVALIDOAUTHURL"

	StatusCodeINVALIDOPERATION StatusCode = "INVALIDOPERATION"

	StatusCodeINVALIDOPERATOR StatusCode = "INVALIDOPERATOR"

	StatusCodeINVALIDORNULLFORRESTRICTEDPICKLIST StatusCode = "INVALIDORNULLFORRESTRICTEDPICKLIST"

	StatusCodeINVALIDOWNER StatusCode = "INVALIDOWNER"

	StatusCodeINVALIDPACKAGELICENSE StatusCode = "INVALIDPACKAGELICENSE"

	StatusCodeINVALIDPACKAGEVERSION StatusCode = "INVALIDPACKAGEVERSION"

	StatusCodeINVALIDPARTNERNETWORKSTATUS StatusCode = "INVALIDPARTNERNETWORKSTATUS"

	StatusCodeINVALIDPERSONACCOUNTOPERATION StatusCode = "INVALIDPERSONACCOUNTOPERATION"

	StatusCodeINVALIDQUERYLOCATOR StatusCode = "INVALIDQUERYLOCATOR"

	StatusCodeINVALIDREADONLYUSERDML StatusCode = "INVALIDREADONLYUSERDML"

	StatusCodeINVALIDRUNTIMEVALUE StatusCode = "INVALIDRUNTIMEVALUE"

	StatusCodeINVALIDSAVEASACTIVITYFLAG StatusCode = "INVALIDSAVEASACTIVITYFLAG"

	StatusCodeINVALIDSESSIONID StatusCode = "INVALIDSESSIONID"

	StatusCodeINVALIDSETUPOWNER StatusCode = "INVALIDSETUPOWNER"

	StatusCodeINVALIDSIGNUPCOUNTRY StatusCode = "INVALIDSIGNUPCOUNTRY"

	StatusCodeINVALIDSIGNUPOPTION StatusCode = "INVALIDSIGNUPOPTION"

	StatusCodeINVALIDSITEDELETEEXCEPTION StatusCode = "INVALIDSITEDELETEEXCEPTION"

	StatusCodeINVALIDSITEFILEIMPORTEDEXCEPTION StatusCode = "INVALIDSITEFILEIMPORTEDEXCEPTION"

	StatusCodeINVALIDSITEFILETYPEEXCEPTION StatusCode = "INVALIDSITEFILETYPEEXCEPTION"

	StatusCodeINVALIDSTATUS StatusCode = "INVALIDSTATUS"

	StatusCodeINVALIDSUBDOMAIN StatusCode = "INVALIDSUBDOMAIN"

	StatusCodeINVALIDTYPE StatusCode = "INVALIDTYPE"

	StatusCodeINVALIDTYPEFOROPERATION StatusCode = "INVALIDTYPEFOROPERATION"

	StatusCodeINVALIDTYPEONFIELDINRECORD StatusCode = "INVALIDTYPEONFIELDINRECORD"

	StatusCodeINVALIDUSERID StatusCode = "INVALIDUSERID"

	StatusCodeIPRANGELIMITEXCEEDED StatusCode = "IPRANGELIMITEXCEEDED"

	StatusCodeJIGSAWIMPORTLIMITEXCEEDED StatusCode = "JIGSAWIMPORTLIMITEXCEEDED"

	StatusCodeLICENSELIMITEXCEEDED StatusCode = "LICENSELIMITEXCEEDED"

	StatusCodeLIGHTPORTALUSEREXCEPTION StatusCode = "LIGHTPORTALUSEREXCEPTION"

	StatusCodeLIMITEXCEEDED StatusCode = "LIMITEXCEEDED"

	StatusCodeMALFORMEDID StatusCode = "MALFORMEDID"

	StatusCodeMANAGERNOTDEFINED StatusCode = "MANAGERNOTDEFINED"

	StatusCodeMASSMAILRETRYLIMITEXCEEDED StatusCode = "MASSMAILRETRYLIMITEXCEEDED"

	StatusCodeMASSMAILLIMITEXCEEDED StatusCode = "MASSMAILLIMITEXCEEDED"

	StatusCodeMATCHDEFINITIONERROR StatusCode = "MATCHDEFINITIONERROR"

	StatusCodeMATCHOPERATIONERROR StatusCode = "MATCHOPERATIONERROR"

	StatusCodeMATCHOPERATIONINVALIDENGINEERROR StatusCode = "MATCHOPERATIONINVALIDENGINEERROR"

	StatusCodeMATCHOPERATIONINVALIDRULEERROR StatusCode = "MATCHOPERATIONINVALIDRULEERROR"

	StatusCodeMATCHOPERATIONMISSINGENGINEERROR StatusCode = "MATCHOPERATIONMISSINGENGINEERROR"

	StatusCodeMATCHOPERATIONMISSINGOBJECTTYPEERROR StatusCode = "MATCHOPERATIONMISSINGOBJECTTYPEERROR"

	StatusCodeMATCHOPERATIONMISSINGOPTIONSERROR StatusCode = "MATCHOPERATIONMISSINGOPTIONSERROR"

	StatusCodeMATCHOPERATIONMISSINGRULEERROR StatusCode = "MATCHOPERATIONMISSINGRULEERROR"

	StatusCodeMATCHOPERATIONUNKNOWNRULEERROR StatusCode = "MATCHOPERATIONUNKNOWNRULEERROR"

	StatusCodeMATCHOPERATIONUNSUPPORTEDVERSIONERROR StatusCode = "MATCHOPERATIONUNSUPPORTEDVERSIONERROR"

	StatusCodeMATCHPRECONDITIONFAILED StatusCode = "MATCHPRECONDITIONFAILED"

	StatusCodeMATCHRUNTIMEERROR StatusCode = "MATCHRUNTIMEERROR"

	StatusCodeMATCHSERVICEERROR StatusCode = "MATCHSERVICEERROR"

	StatusCodeMATCHSERVICETIMEDOUT StatusCode = "MATCHSERVICETIMEDOUT"

	StatusCodeMATCHSERVICEUNAVAILABLEERROR StatusCode = "MATCHSERVICEUNAVAILABLEERROR"

	StatusCodeMAXIMUMCCEMAILSEXCEEDED StatusCode = "MAXIMUMCCEMAILSEXCEEDED"

	StatusCodeMAXIMUMDASHBOARDCOMPONENTSEXCEEDED StatusCode = "MAXIMUMDASHBOARDCOMPONENTSEXCEEDED"

	StatusCodeMAXIMUMHIERARCHYCHILDRENREACHED StatusCode = "MAXIMUMHIERARCHYCHILDRENREACHED"

	StatusCodeMAXIMUMHIERARCHYLEVELSREACHED StatusCode = "MAXIMUMHIERARCHYLEVELSREACHED"

	StatusCodeMAXIMUMHIERARCHYTREESIZEREACHED StatusCode = "MAXIMUMHIERARCHYTREESIZEREACHED"

	StatusCodeMAXIMUMSIZEOFATTACHMENT StatusCode = "MAXIMUMSIZEOFATTACHMENT"

	StatusCodeMAXIMUMSIZEOFDOCUMENT StatusCode = "MAXIMUMSIZEOFDOCUMENT"

	StatusCodeMAXACTIONSPERRULEEXCEEDED StatusCode = "MAXACTIONSPERRULEEXCEEDED"

	StatusCodeMAXACTIVERULESEXCEEDED StatusCode = "MAXACTIVERULESEXCEEDED"

	StatusCodeMAXAPPROVALSTEPSEXCEEDED StatusCode = "MAXAPPROVALSTEPSEXCEEDED"

	StatusCodeMAXDEPTHINFLOWEXECUTION StatusCode = "MAXDEPTHINFLOWEXECUTION"

	StatusCodeMAXFORMULASPERRULEEXCEEDED StatusCode = "MAXFORMULASPERRULEEXCEEDED"

	StatusCodeMAXRULESEXCEEDED StatusCode = "MAXRULESEXCEEDED"

	StatusCodeMAXRULEENTRIESEXCEEDED StatusCode = "MAXRULEENTRIESEXCEEDED"

	StatusCodeMAXTASKDESCRIPTIONEXCEEEDED StatusCode = "MAXTASKDESCRIPTIONEXCEEEDED"

	StatusCodeMAXTMRULESEXCEEDED StatusCode = "MAXTMRULESEXCEEDED"

	StatusCodeMAXTMRULEITEMSEXCEEDED StatusCode = "MAXTMRULEITEMSEXCEEDED"

	StatusCodeMERGEFAILED StatusCode = "MERGEFAILED"

	StatusCodeMETADATAFIELDUPDATEERROR StatusCode = "METADATAFIELDUPDATEERROR"

	StatusCodeMISSINGARGUMENT StatusCode = "MISSINGARGUMENT"

	StatusCodeMISSINGRECORD StatusCode = "MISSINGRECORD"

	StatusCodeMIXEDDMLOPERATION StatusCode = "MIXEDDMLOPERATION"

	StatusCodeNONUNIQUESHIPPINGADDRESS StatusCode = "NONUNIQUESHIPPINGADDRESS"

	StatusCodeNOAPPLICABLEPROCESS StatusCode = "NOAPPLICABLEPROCESS"

	StatusCodeNOATTACHMENTPERMISSION StatusCode = "NOATTACHMENTPERMISSION"

	StatusCodeNOINACTIVEDIVISIONMEMBERS StatusCode = "NOINACTIVEDIVISIONMEMBERS"

	StatusCodeNOMASSMAILPERMISSION StatusCode = "NOMASSMAILPERMISSION"

	StatusCodeNOPARTNERPERMISSION StatusCode = "NOPARTNERPERMISSION"

	StatusCodeNOSUCHUSEREXISTS StatusCode = "NOSUCHUSEREXISTS"

	StatusCodeNUMBEROUTSIDEVALIDRANGE StatusCode = "NUMBEROUTSIDEVALIDRANGE"

	StatusCodeNUMHISTORYFIELDSBYSOBJECTEXCEEDED StatusCode = "NUMHISTORYFIELDSBYSOBJECTEXCEEDED"

	StatusCodeOPTEDOUTOFMASSMAIL StatusCode = "OPTEDOUTOFMASSMAIL"

	StatusCodeOPWITHINVALIDUSERTYPEEXCEPTION StatusCode = "OPWITHINVALIDUSERTYPEEXCEPTION"

	StatusCodePACKAGELICENSEREQUIRED StatusCode = "PACKAGELICENSEREQUIRED"

	StatusCodePACKAGINGAPIINSTALLFAILED StatusCode = "PACKAGINGAPIINSTALLFAILED"

	StatusCodePACKAGINGAPIUNINSTALLFAILED StatusCode = "PACKAGINGAPIUNINSTALLFAILED"

	StatusCodePALIINVALIDACTIONID StatusCode = "PALIINVALIDACTIONID"

	StatusCodePALIINVALIDACTIONNAME StatusCode = "PALIINVALIDACTIONNAME"

	StatusCodePALIINVALIDACTIONTYPE StatusCode = "PALIINVALIDACTIONTYPE"

	StatusCodePALINVALIDASSISTANTRECOMMENDATIONTYPEID StatusCode = "PALINVALIDASSISTANTRECOMMENDATIONTYPEID"

	StatusCodePALINVALIDENTITYID StatusCode = "PALINVALIDENTITYID"

	StatusCodePALINVALIDFLEXIPAGEID StatusCode = "PALINVALIDFLEXIPAGEID"

	StatusCodePALINVALIDLAYOUTID StatusCode = "PALINVALIDLAYOUTID"

	StatusCodePALINVALIDPARAMETERS StatusCode = "PALINVALIDPARAMETERS"

	StatusCodePAAPIEXCEPTION StatusCode = "PAAPIEXCEPTION"

	StatusCodePAAXISFAULT StatusCode = "PAAXISFAULT"

	StatusCodePAINVALIDIDEXCEPTION StatusCode = "PAINVALIDIDEXCEPTION"

	StatusCodePANOACCESSEXCEPTION StatusCode = "PANOACCESSEXCEPTION"

	StatusCodePANODATAFOUNDEXCEPTION StatusCode = "PANODATAFOUNDEXCEPTION"

	StatusCodePAURISYNTAXEXCEPTION StatusCode = "PAURISYNTAXEXCEPTION"

	StatusCodePAVISIBLEACTIONSFILTERORDERINGEXCEPTION StatusCode = "PAVISIBLEACTIONSFILTERORDERINGEXCEPTION"

	StatusCodePORTALNOACCESS StatusCode = "PORTALNOACCESS"

	StatusCodePORTALUSERALREADYEXISTSFORCONTACT StatusCode = "PORTALUSERALREADYEXISTSFORCONTACT"

	StatusCodePORTALUSERCREATIONRESTRICTEDWITHENCRYPTION StatusCode = "PORTALUSERCREATIONRESTRICTEDWITHENCRYPTION"

	StatusCodePRIVATECONTACTONASSET StatusCode = "PRIVATECONTACTONASSET"

	StatusCodePROCESSINGHALTED StatusCode = "PROCESSINGHALTED"

	StatusCodeQAINVALIDCREATEFEEDITEM StatusCode = "QAINVALIDCREATEFEEDITEM"

	StatusCodeQAINVALIDSUCCESSMESSAGE StatusCode = "QAINVALIDSUCCESSMESSAGE"

	StatusCodeQUERYTIMEOUT StatusCode = "QUERYTIMEOUT"

	StatusCodeQUICKACTIONLISTITEMNOTALLOWED StatusCode = "QUICKACTIONLISTITEMNOTALLOWED"

	StatusCodeQUICKACTIONLISTNOTALLOWED StatusCode = "QUICKACTIONLISTNOTALLOWED"

	StatusCodeRECORDINUSEBYWORKFLOW StatusCode = "RECORDINUSEBYWORKFLOW"

	StatusCodeRELFIELDBADACCESSIBILITY StatusCode = "RELFIELDBADACCESSIBILITY"

	StatusCodeREPUTATIONMINIMUMNUMBERNOTREACHED StatusCode = "REPUTATIONMINIMUMNUMBERNOTREACHED"

	StatusCodeREQUESTRUNNINGTOOLONG StatusCode = "REQUESTRUNNINGTOOLONG"

	StatusCodeREQUIREDFEATUREMISSING StatusCode = "REQUIREDFEATUREMISSING"

	StatusCodeREQUIREDFIELDMISSING StatusCode = "REQUIREDFIELDMISSING"

	StatusCodeRETRIEVEEXCHANGEATTACHMENTFAILED StatusCode = "RETRIEVEEXCHANGEATTACHMENTFAILED"

	StatusCodeRETRIEVEEXCHANGEEMAILFAILED StatusCode = "RETRIEVEEXCHANGEEMAILFAILED"

	StatusCodeRETRIEVEEXCHANGEEVENTFAILED StatusCode = "RETRIEVEEXCHANGEEVENTFAILED"

	StatusCodeSALESFORCEINBOXTRANSPORTCONNECTIONERROR StatusCode = "SALESFORCEINBOXTRANSPORTCONNECTIONERROR"

	StatusCodeSALESFORCEINBOXTRANSPORTTOKENERROR StatusCode = "SALESFORCEINBOXTRANSPORTTOKENERROR"

	StatusCodeSALESFORCEINBOXTRANSPORTUNKNOWNERROR StatusCode = "SALESFORCEINBOXTRANSPORTUNKNOWNERROR"

	StatusCodeSELFREFERENCEFROMFLOW StatusCode = "SELFREFERENCEFROMFLOW"

	StatusCodeSELFREFERENCEFROMTRIGGER StatusCode = "SELFREFERENCEFROMTRIGGER"

	StatusCodeSHARENEEDEDFORCHILDOWNER StatusCode = "SHARENEEDEDFORCHILDOWNER"

	StatusCodeSINGLEEMAILLIMITEXCEEDED StatusCode = "SINGLEEMAILLIMITEXCEEDED"

	StatusCodeSOCIALACCOUNTNOTFOUND StatusCode = "SOCIALACCOUNTNOTFOUND"

	StatusCodeSOCIALACTIONINVALID StatusCode = "SOCIALACTIONINVALID"

	StatusCodeSOCIALPOSTINVALID StatusCode = "SOCIALPOSTINVALID"

	StatusCodeSOCIALPOSTNOTFOUND StatusCode = "SOCIALPOSTNOTFOUND"

	StatusCodeSTANDARDPRICENOTDEFINED StatusCode = "STANDARDPRICENOTDEFINED"

	StatusCodeSTORAGELIMITEXCEEDED StatusCode = "STORAGELIMITEXCEEDED"

	StatusCodeSTRINGTOOLONG StatusCode = "STRINGTOOLONG"

	StatusCodeSUBDOMAININUSE StatusCode = "SUBDOMAININUSE"

	StatusCodeTABSETLIMITEXCEEDED StatusCode = "TABSETLIMITEXCEEDED"

	StatusCodeTEMPLATENOTACTIVE StatusCode = "TEMPLATENOTACTIVE"

	StatusCodeTEMPLATENOTFOUND StatusCode = "TEMPLATENOTFOUND"

	StatusCodeTERRITORYREALIGNINPROGRESS StatusCode = "TERRITORYREALIGNINPROGRESS"

	StatusCodeTEXTDATAOUTSIDESUPPORTEDCHARSET StatusCode = "TEXTDATAOUTSIDESUPPORTEDCHARSET"

	StatusCodeTOOMANYAPEXREQUESTS StatusCode = "TOOMANYAPEXREQUESTS"

	StatusCodeTOOMANYENUMVALUE StatusCode = "TOOMANYENUMVALUE"

	StatusCodeTOOMANYPOSSIBLEUSERSEXIST StatusCode = "TOOMANYPOSSIBLEUSERSEXIST"

	StatusCodeTRANSFERREQUIRESREAD StatusCode = "TRANSFERREQUIRESREAD"

	StatusCodeUNABLETOLOCKROW StatusCode = "UNABLETOLOCKROW"

	StatusCodeUNAVAILABLERECORDTYPEEXCEPTION StatusCode = "UNAVAILABLERECORDTYPEEXCEPTION"

	StatusCodeUNAVAILABLEREF StatusCode = "UNAVAILABLEREF"

	StatusCodeUNDELETEFAILED StatusCode = "UNDELETEFAILED"

	StatusCodeUNKNOWNEXCEPTION StatusCode = "UNKNOWNEXCEPTION"

	StatusCodeUNSAFEHTMLCONTENT StatusCode = "UNSAFEHTMLCONTENT"

	StatusCodeUNSPECIFIEDEMAILADDRESS StatusCode = "UNSPECIFIEDEMAILADDRESS"

	StatusCodeUNSUPPORTEDAPEXTRIGGEROPERATON StatusCode = "UNSUPPORTEDAPEXTRIGGEROPERATON"

	StatusCodeUNVERIFIEDSENDERADDRESS StatusCode = "UNVERIFIEDSENDERADDRESS"

	StatusCodeUSEROWNSPORTALACCOUNTEXCEPTION StatusCode = "USEROWNSPORTALACCOUNTEXCEPTION"

	StatusCodeUSERWITHAPEXSHARESEXCEPTION StatusCode = "USERWITHAPEXSHARESEXCEPTION"

	StatusCodeVFCOMPILEERROR StatusCode = "VFCOMPILEERROR"

	StatusCodeWEBLINKSIZELIMITEXCEEDED StatusCode = "WEBLINKSIZELIMITEXCEEDED"

	StatusCodeWEBLINKURLINVALID StatusCode = "WEBLINKURLINVALID"

	StatusCodeWRONGCONTROLLERTYPE StatusCode = "WRONGCONTROLLERTYPE"

	StatusCodeXCLEANUNEXPECTEDERROR StatusCode = "XCLEANUNEXPECTEDERROR"
)
