FROM autokit/micro-builder:latest as builder

WORKDIR /opt

RUN go env -w GOPROXY=https://goproxy.cn,direct && go env -w GO111MODULE=on
ADD go.mod .
RUN go mod download

COPY . /opt

VOLUME /opt/build