// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SObject struct {
	OrgId                string            `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	Type                 string            `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	FieldsToNull         []string          `protobuf:"bytes,3,rep,name=fieldsToNull,proto3" json:"fieldsToNull,omitempty"`
	Id                   string            `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Fields               map[string]string `protobuf:"bytes,5,rep,name=Fields,proto3" json:"Fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SObject) Reset()         { *m = SObject{} }
func (m *SObject) String() string { return proto.CompactTextString(m) }
func (*SObject) ProtoMessage()    {}
func (*SObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *SObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SObject.Unmarshal(m, b)
}
func (m *SObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SObject.Marshal(b, m, deterministic)
}
func (m *SObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SObject.Merge(m, src)
}
func (m *SObject) XXX_Size() int {
	return xxx_messageInfo_SObject.Size(m)
}
func (m *SObject) XXX_DiscardUnknown() {
	xxx_messageInfo_SObject.DiscardUnknown(m)
}

var xxx_messageInfo_SObject proto.InternalMessageInfo

func (m *SObject) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *SObject) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SObject) GetFieldsToNull() []string {
	if m != nil {
		return m.FieldsToNull
	}
	return nil
}

func (m *SObject) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SObject) GetFields() map[string]string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type CreateSObjectRequest struct {
	Objects              []*SObject `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateSObjectRequest) Reset()         { *m = CreateSObjectRequest{} }
func (m *CreateSObjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSObjectRequest) ProtoMessage()    {}
func (*CreateSObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *CreateSObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSObjectRequest.Unmarshal(m, b)
}
func (m *CreateSObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSObjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateSObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSObjectRequest.Merge(m, src)
}
func (m *CreateSObjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSObjectRequest.Size(m)
}
func (m *CreateSObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSObjectRequest proto.InternalMessageInfo

func (m *CreateSObjectRequest) GetObjects() []*SObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

type CreateSObjectResponse struct {
	Results              []*SaveResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateSObjectResponse) Reset()         { *m = CreateSObjectResponse{} }
func (m *CreateSObjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSObjectResponse) ProtoMessage()    {}
func (*CreateSObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *CreateSObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSObjectResponse.Unmarshal(m, b)
}
func (m *CreateSObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSObjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateSObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSObjectResponse.Merge(m, src)
}
func (m *CreateSObjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSObjectResponse.Size(m)
}
func (m *CreateSObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSObjectResponse proto.InternalMessageInfo

func (m *CreateSObjectResponse) GetResults() []*SaveResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type UpdateSObjectRequest struct {
	Objects              []*SObject `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateSObjectRequest) Reset()         { *m = UpdateSObjectRequest{} }
func (m *UpdateSObjectRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSObjectRequest) ProtoMessage()    {}
func (*UpdateSObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *UpdateSObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSObjectRequest.Unmarshal(m, b)
}
func (m *UpdateSObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSObjectRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSObjectRequest.Merge(m, src)
}
func (m *UpdateSObjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSObjectRequest.Size(m)
}
func (m *UpdateSObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSObjectRequest proto.InternalMessageInfo

func (m *UpdateSObjectRequest) GetObjects() []*SObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

type UpdateSObjectResponse struct {
	Results              []*SaveResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateSObjectResponse) Reset()         { *m = UpdateSObjectResponse{} }
func (m *UpdateSObjectResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSObjectResponse) ProtoMessage()    {}
func (*UpdateSObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *UpdateSObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSObjectResponse.Unmarshal(m, b)
}
func (m *UpdateSObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSObjectResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSObjectResponse.Merge(m, src)
}
func (m *UpdateSObjectResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSObjectResponse.Size(m)
}
func (m *UpdateSObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSObjectResponse proto.InternalMessageInfo

func (m *UpdateSObjectResponse) GetResults() []*SaveResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type UpsertSObjectRequest struct {
	ExternalIDFieldName  string     `protobuf:"bytes,1,opt,name=ExternalIDFieldName,proto3" json:"ExternalIDFieldName,omitempty"`
	Objects              []*SObject `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpsertSObjectRequest) Reset()         { *m = UpsertSObjectRequest{} }
func (m *UpsertSObjectRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertSObjectRequest) ProtoMessage()    {}
func (*UpsertSObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{5}
}

func (m *UpsertSObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertSObjectRequest.Unmarshal(m, b)
}
func (m *UpsertSObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertSObjectRequest.Marshal(b, m, deterministic)
}
func (m *UpsertSObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertSObjectRequest.Merge(m, src)
}
func (m *UpsertSObjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertSObjectRequest.Size(m)
}
func (m *UpsertSObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertSObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertSObjectRequest proto.InternalMessageInfo

func (m *UpsertSObjectRequest) GetExternalIDFieldName() string {
	if m != nil {
		return m.ExternalIDFieldName
	}
	return ""
}

func (m *UpsertSObjectRequest) GetObjects() []*SObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

type UpsertSObjectResponse struct {
	Results              []*UpsertSObjectResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UpsertSObjectResponse) Reset()         { *m = UpsertSObjectResponse{} }
func (m *UpsertSObjectResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertSObjectResponse) ProtoMessage()    {}
func (*UpsertSObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{6}
}

func (m *UpsertSObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertSObjectResponse.Unmarshal(m, b)
}
func (m *UpsertSObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertSObjectResponse.Marshal(b, m, deterministic)
}
func (m *UpsertSObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertSObjectResponse.Merge(m, src)
}
func (m *UpsertSObjectResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertSObjectResponse.Size(m)
}
func (m *UpsertSObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertSObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertSObjectResponse proto.InternalMessageInfo

func (m *UpsertSObjectResponse) GetResults() []*UpsertSObjectResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type UpsertSObjectResult struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Errors               []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertSObjectResult) Reset()         { *m = UpsertSObjectResult{} }
func (m *UpsertSObjectResult) String() string { return proto.CompactTextString(m) }
func (*UpsertSObjectResult) ProtoMessage()    {}
func (*UpsertSObjectResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{7}
}

func (m *UpsertSObjectResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertSObjectResult.Unmarshal(m, b)
}
func (m *UpsertSObjectResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertSObjectResult.Marshal(b, m, deterministic)
}
func (m *UpsertSObjectResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertSObjectResult.Merge(m, src)
}
func (m *UpsertSObjectResult) XXX_Size() int {
	return xxx_messageInfo_UpsertSObjectResult.Size(m)
}
func (m *UpsertSObjectResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertSObjectResult.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertSObjectResult proto.InternalMessageInfo

func (m *UpsertSObjectResult) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *UpsertSObjectResult) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *UpsertSObjectResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpsertSObjectResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RetrieveSObjectRequest struct {
	OrgId                string   `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	Ids                  []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	Fields               []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveSObjectRequest) Reset()         { *m = RetrieveSObjectRequest{} }
func (m *RetrieveSObjectRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveSObjectRequest) ProtoMessage()    {}
func (*RetrieveSObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{8}
}

func (m *RetrieveSObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveSObjectRequest.Unmarshal(m, b)
}
func (m *RetrieveSObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveSObjectRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveSObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveSObjectRequest.Merge(m, src)
}
func (m *RetrieveSObjectRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveSObjectRequest.Size(m)
}
func (m *RetrieveSObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveSObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveSObjectRequest proto.InternalMessageInfo

func (m *RetrieveSObjectRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *RetrieveSObjectRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *RetrieveSObjectRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *RetrieveSObjectRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type RetrieveSObjectResponse struct {
	Results              []*SObject `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RetrieveSObjectResponse) Reset()         { *m = RetrieveSObjectResponse{} }
func (m *RetrieveSObjectResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveSObjectResponse) ProtoMessage()    {}
func (*RetrieveSObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{9}
}

func (m *RetrieveSObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveSObjectResponse.Unmarshal(m, b)
}
func (m *RetrieveSObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveSObjectResponse.Marshal(b, m, deterministic)
}
func (m *RetrieveSObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveSObjectResponse.Merge(m, src)
}
func (m *RetrieveSObjectResponse) XXX_Size() int {
	return xxx_messageInfo_RetrieveSObjectResponse.Size(m)
}
func (m *RetrieveSObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveSObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveSObjectResponse proto.InternalMessageInfo

func (m *RetrieveSObjectResponse) GetResults() []*SObject {
	if m != nil {
		return m.Results
	}
	return nil
}

type DeleteSObjectRequest struct {
	OrgId                string   `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	Ids                  []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSObjectRequest) Reset()         { *m = DeleteSObjectRequest{} }
func (m *DeleteSObjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSObjectRequest) ProtoMessage()    {}
func (*DeleteSObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{10}
}

func (m *DeleteSObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSObjectRequest.Unmarshal(m, b)
}
func (m *DeleteSObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSObjectRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSObjectRequest.Merge(m, src)
}
func (m *DeleteSObjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSObjectRequest.Size(m)
}
func (m *DeleteSObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSObjectRequest proto.InternalMessageInfo

func (m *DeleteSObjectRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *DeleteSObjectRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *DeleteSObjectRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type DeleteSObjectResponse struct {
	Results              []*DeleteResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DeleteSObjectResponse) Reset()         { *m = DeleteSObjectResponse{} }
func (m *DeleteSObjectResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSObjectResponse) ProtoMessage()    {}
func (*DeleteSObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{11}
}

func (m *DeleteSObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSObjectResponse.Unmarshal(m, b)
}
func (m *DeleteSObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSObjectResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSObjectResponse.Merge(m, src)
}
func (m *DeleteSObjectResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSObjectResponse.Size(m)
}
func (m *DeleteSObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSObjectResponse proto.InternalMessageInfo

func (m *DeleteSObjectResponse) GetResults() []*DeleteResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type DeleteResult struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResult) Reset()         { *m = DeleteResult{} }
func (m *DeleteResult) String() string { return proto.CompactTextString(m) }
func (*DeleteResult) ProtoMessage()    {}
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{12}
}

func (m *DeleteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResult.Unmarshal(m, b)
}
func (m *DeleteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResult.Marshal(b, m, deterministic)
}
func (m *DeleteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResult.Merge(m, src)
}
func (m *DeleteResult) XXX_Size() int {
	return xxx_messageInfo_DeleteResult.Size(m)
}
func (m *DeleteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResult proto.InternalMessageInfo

func (m *DeleteResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DeleteResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SaveResult struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResult) Reset()         { *m = SaveResult{} }
func (m *SaveResult) String() string { return proto.CompactTextString(m) }
func (*SaveResult) ProtoMessage()    {}
func (*SaveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{13}
}

func (m *SaveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResult.Unmarshal(m, b)
}
func (m *SaveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResult.Marshal(b, m, deterministic)
}
func (m *SaveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResult.Merge(m, src)
}
func (m *SaveResult) XXX_Size() int {
	return xxx_messageInfo_SaveResult.Size(m)
}
func (m *SaveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResult.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResult proto.InternalMessageInfo

func (m *SaveResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SaveResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SaveResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode           int32    `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{14}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*SObject)(nil), "data.SObject")
	proto.RegisterMapType((map[string]string)(nil), "data.SObject.FieldsEntry")
	proto.RegisterType((*CreateSObjectRequest)(nil), "data.CreateSObjectRequest")
	proto.RegisterType((*CreateSObjectResponse)(nil), "data.CreateSObjectResponse")
	proto.RegisterType((*UpdateSObjectRequest)(nil), "data.UpdateSObjectRequest")
	proto.RegisterType((*UpdateSObjectResponse)(nil), "data.UpdateSObjectResponse")
	proto.RegisterType((*UpsertSObjectRequest)(nil), "data.UpsertSObjectRequest")
	proto.RegisterType((*UpsertSObjectResponse)(nil), "data.UpsertSObjectResponse")
	proto.RegisterType((*UpsertSObjectResult)(nil), "data.UpsertSObjectResult")
	proto.RegisterType((*RetrieveSObjectRequest)(nil), "data.RetrieveSObjectRequest")
	proto.RegisterType((*RetrieveSObjectResponse)(nil), "data.RetrieveSObjectResponse")
	proto.RegisterType((*DeleteSObjectRequest)(nil), "data.DeleteSObjectRequest")
	proto.RegisterType((*DeleteSObjectResponse)(nil), "data.DeleteSObjectResponse")
	proto.RegisterType((*DeleteResult)(nil), "data.DeleteResult")
	proto.RegisterType((*SaveResult)(nil), "data.SaveResult")
	proto.RegisterType((*Error)(nil), "data.Error")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0x5b, 0x4f, 0x13, 0x41,
	0x14, 0xc7, 0xdb, 0xdd, 0xd2, 0xc2, 0x01, 0x09, 0x19, 0x0a, 0x2e, 0xf5, 0x92, 0x66, 0x7d, 0xa0,
	0x31, 0xa6, 0x28, 0xbc, 0xa8, 0x2f, 0x46, 0x4a, 0x4d, 0x9a, 0x90, 0x9a, 0x0c, 0xfa, 0xe2, 0xdb,
	0xb6, 0x7b, 0x68, 0x56, 0x97, 0x6e, 0x99, 0x99, 0x6d, 0xec, 0x8b, 0xdf, 0xd2, 0xcf, 0xe1, 0x57,
	0x30, 0x73, 0x6b, 0xb7, 0xcb, 0x68, 0x22, 0xbe, 0xed, 0xb9, 0xf0, 0x9f, 0x1f, 0xe7, 0x56, 0x80,
	0x38, 0x12, 0x51, 0x77, 0xc6, 0x32, 0x91, 0x91, 0x9a, 0xfc, 0x6e, 0x1d, 0x4d, 0xb2, 0x6c, 0x92,
	0xe2, 0x89, 0xf2, 0x8d, 0xf2, 0xeb, 0x93, 0x68, 0xba, 0xd0, 0x09, 0xe1, 0xcf, 0x2a, 0x34, 0xae,
	0x3e, 0x8e, 0xbe, 0xe2, 0x58, 0x90, 0x26, 0x6c, 0x64, 0x6c, 0x32, 0x88, 0x83, 0x6a, 0xbb, 0xda,
	0xd9, 0xa2, 0xda, 0x20, 0x04, 0x6a, 0x62, 0x31, 0xc3, 0xc0, 0x53, 0x4e, 0xf5, 0x4d, 0x42, 0xd8,
	0xb9, 0x4e, 0x30, 0x8d, 0xf9, 0xa7, 0x6c, 0x98, 0xa7, 0x69, 0xe0, 0xb7, 0xfd, 0xce, 0x16, 0x5d,
	0xf3, 0x91, 0x5d, 0xf0, 0x92, 0x38, 0xa8, 0xa9, 0xbf, 0xf2, 0x92, 0x98, 0xbc, 0x82, 0xfa, 0x07,
	0x15, 0x0f, 0x36, 0xda, 0x7e, 0x67, 0xfb, 0xf4, 0xa8, 0xab, 0x38, 0xcd, 0xe3, 0x5d, 0x1d, 0xeb,
	0x4f, 0x05, 0x5b, 0x50, 0x93, 0xd8, 0x7a, 0x03, 0xdb, 0x05, 0x37, 0xd9, 0x03, 0xff, 0x1b, 0x2e,
	0x0c, 0x9d, 0xfc, 0x94, 0xc4, 0xf3, 0x28, 0xcd, 0x2d, 0x9c, 0x36, 0xde, 0x7a, 0xaf, 0xab, 0xe1,
	0x3b, 0x68, 0xf6, 0x18, 0x46, 0x02, 0x8d, 0x3e, 0xc5, 0xdb, 0x1c, 0xb9, 0x20, 0xc7, 0xd0, 0xc8,
	0x94, 0x83, 0x07, 0x55, 0x85, 0xf1, 0x60, 0x0d, 0x83, 0xda, 0x68, 0xd8, 0x83, 0x83, 0x92, 0x00,
	0x9f, 0x65, 0x53, 0x8e, 0xe4, 0x39, 0x34, 0x18, 0xf2, 0x3c, 0x5d, 0x2a, 0xec, 0x19, 0x85, 0x68,
	0x8e, 0x54, 0x05, 0xa8, 0x4d, 0x90, 0x14, 0x9f, 0x67, 0xf1, 0xff, 0x51, 0x94, 0x04, 0xee, 0x41,
	0x71, 0x2b, 0x29, 0x38, 0x32, 0x51, 0xa2, 0x78, 0x09, 0xfb, 0xfd, 0xef, 0x02, 0xd9, 0x34, 0x4a,
	0x07, 0x17, 0xaa, 0xd0, 0xc3, 0xe8, 0x06, 0x4d, 0x7d, 0x5d, 0xa1, 0x22, 0xb7, 0xf7, 0x57, 0xee,
	0x4b, 0xc9, 0xbd, 0xf6, 0xa4, 0xe1, 0x3e, 0x2b, 0x73, 0x9b, 0x31, 0x28, 0x67, 0xaf, 0xfd, 0x03,
	0x3f, 0x60, 0xdf, 0x11, 0x27, 0x01, 0x34, 0xc6, 0xaa, 0x45, 0x7a, 0x62, 0x37, 0xa9, 0x35, 0xc9,
	0x33, 0xa8, 0x23, 0x63, 0x19, 0xb3, 0x98, 0xdb, 0xfa, 0x91, 0xbe, 0xf4, 0x51, 0x13, 0x32, 0x03,
	0xea, 0x2f, 0x07, 0x34, 0x80, 0x06, 0xcf, 0xc7, 0x63, 0xe4, 0x5c, 0x4d, 0xed, 0x26, 0xb5, 0x66,
	0x98, 0xc2, 0x21, 0x45, 0xc1, 0x12, 0x9c, 0x97, 0x1b, 0xe9, 0x5e, 0x99, 0x3d, 0xf0, 0x93, 0x58,
	0xbf, 0xbd, 0x45, 0xe5, 0x27, 0x39, 0x84, 0xba, 0x5e, 0x0e, 0xb3, 0x2a, 0xc6, 0x5a, 0x2e, 0x57,
	0x6d, 0xb5, 0x5c, 0xe1, 0x39, 0x3c, 0xbc, 0xf3, 0x9a, 0xa9, 0xde, 0x71, 0xb9, 0x7a, 0xe5, 0xfa,
	0xdb, 0x8a, 0x51, 0x68, 0x5e, 0x60, 0x8a, 0xe2, 0xbe, 0xbc, 0x96, 0xcb, 0x2f, 0x70, 0xf5, 0xe1,
	0xa0, 0xa4, 0x69, 0xa8, 0x5e, 0x94, 0xa9, 0x88, 0xa6, 0xd2, 0xd9, 0xe5, 0x66, 0x0e, 0x61, 0xa7,
	0x18, 0x90, 0x48, 0xaa, 0x2f, 0x16, 0x49, 0x19, 0xa6, 0x39, 0x9e, 0xab, 0x39, 0xfe, 0x7a, 0x73,
	0x2e, 0x01, 0x56, 0x43, 0x2f, 0xd5, 0xb0, 0xa8, 0x86, 0xff, 0xa8, 0xf6, 0xde, 0xd0, 0xc8, 0x94,
	0x1b, 0xe4, 0x3c, 0x9a, 0xd8, 0x85, 0xb0, 0x26, 0x79, 0x0a, 0xc0, 0x45, 0x24, 0x72, 0xde, 0xcb,
	0x62, 0x7d, 0x79, 0x36, 0x68, 0xc1, 0x73, 0xfa, 0xcb, 0x83, 0x5d, 0x53, 0xa2, 0x2b, 0x64, 0xf3,
	0x64, 0x8c, 0xa4, 0x07, 0x75, 0x7d, 0x4c, 0x48, 0x4b, 0x97, 0xc6, 0x75, 0x9b, 0x5a, 0x8f, 0x9c,
	0x31, 0x5d, 0xe4, 0xb0, 0x22, 0x45, 0xf4, 0x2d, 0xb0, 0x22, 0xae, 0xd3, 0x62, 0x45, 0x9c, 0x57,
	0xc3, 0x8a, 0xc8, 0x55, 0x5a, 0x89, 0xdc, 0xbd, 0x0c, 0x2b, 0x11, 0xc7, 0x0a, 0x87, 0x15, 0x32,
	0x80, 0x4d, 0x3b, 0xa1, 0xe4, 0xb1, 0x4e, 0x75, 0xef, 0x47, 0xeb, 0xc9, 0x1f, 0xa2, 0x45, 0x1e,
	0x3d, 0x0d, 0x96, 0xc7, 0x35, 0xb6, 0x96, 0xc7, 0x39, 0x7e, 0x61, 0xe5, 0xdc, 0xfb, 0x52, 0x19,
	0xd5, 0xd5, 0xef, 0xd9, 0xd9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x6a, 0x41, 0x5d, 0xfe,
	0x06, 0x00, 0x00,
}
