// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: data.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SObjectService service

func NewSObjectServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SObjectService service

type SObjectService interface {
	Create(ctx context.Context, in *CreateSObjectRequest, opts ...client.CallOption) (*CreateSObjectResponse, error)
	Update(ctx context.Context, in *UpdateSObjectRequest, opts ...client.CallOption) (*UpdateSObjectResponse, error)
	Retrieve(ctx context.Context, in *RetrieveSObjectRequest, opts ...client.CallOption) (*RetrieveSObjectResponse, error)
	Delete(ctx context.Context, in *DeleteSObjectRequest, opts ...client.CallOption) (*DeleteSObjectResponse, error)
}

type sObjectService struct {
	c    client.Client
	name string
}

func NewSObjectService(name string, c client.Client) SObjectService {
	return &sObjectService{
		c:    c,
		name: name,
	}
}

func (c *sObjectService) Create(ctx context.Context, in *CreateSObjectRequest, opts ...client.CallOption) (*CreateSObjectResponse, error) {
	req := c.c.NewRequest(c.name, "SObjectService.Create", in)
	out := new(CreateSObjectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sObjectService) Update(ctx context.Context, in *UpdateSObjectRequest, opts ...client.CallOption) (*UpdateSObjectResponse, error) {
	req := c.c.NewRequest(c.name, "SObjectService.Update", in)
	out := new(UpdateSObjectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sObjectService) Retrieve(ctx context.Context, in *RetrieveSObjectRequest, opts ...client.CallOption) (*RetrieveSObjectResponse, error) {
	req := c.c.NewRequest(c.name, "SObjectService.Retrieve", in)
	out := new(RetrieveSObjectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sObjectService) Delete(ctx context.Context, in *DeleteSObjectRequest, opts ...client.CallOption) (*DeleteSObjectResponse, error) {
	req := c.c.NewRequest(c.name, "SObjectService.Delete", in)
	out := new(DeleteSObjectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SObjectService service

type SObjectServiceHandler interface {
	Create(context.Context, *CreateSObjectRequest, *CreateSObjectResponse) error
	Update(context.Context, *UpdateSObjectRequest, *UpdateSObjectResponse) error
	Retrieve(context.Context, *RetrieveSObjectRequest, *RetrieveSObjectResponse) error
	Delete(context.Context, *DeleteSObjectRequest, *DeleteSObjectResponse) error
}

func RegisterSObjectServiceHandler(s server.Server, hdlr SObjectServiceHandler, opts ...server.HandlerOption) error {
	type sObjectService interface {
		Create(ctx context.Context, in *CreateSObjectRequest, out *CreateSObjectResponse) error
		Update(ctx context.Context, in *UpdateSObjectRequest, out *UpdateSObjectResponse) error
		Retrieve(ctx context.Context, in *RetrieveSObjectRequest, out *RetrieveSObjectResponse) error
		Delete(ctx context.Context, in *DeleteSObjectRequest, out *DeleteSObjectResponse) error
	}
	type SObjectService struct {
		sObjectService
	}
	h := &sObjectServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SObjectService{h}, opts...))
}

type sObjectServiceHandler struct {
	SObjectServiceHandler
}

func (h *sObjectServiceHandler) Create(ctx context.Context, in *CreateSObjectRequest, out *CreateSObjectResponse) error {
	return h.SObjectServiceHandler.Create(ctx, in, out)
}

func (h *sObjectServiceHandler) Update(ctx context.Context, in *UpdateSObjectRequest, out *UpdateSObjectResponse) error {
	return h.SObjectServiceHandler.Update(ctx, in, out)
}

func (h *sObjectServiceHandler) Retrieve(ctx context.Context, in *RetrieveSObjectRequest, out *RetrieveSObjectResponse) error {
	return h.SObjectServiceHandler.Retrieve(ctx, in, out)
}

func (h *sObjectServiceHandler) Delete(ctx context.Context, in *DeleteSObjectRequest, out *DeleteSObjectResponse) error {
	return h.SObjectServiceHandler.Delete(ctx, in, out)
}
