// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/meta/meta.proto

package meta // import "github.com/objforce/objforce/proto/meta"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetCustomObjectRequest struct {
	ObjId                string   `protobuf:"bytes,1,opt,name=objId,proto3" json:"objId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomObjectRequest) Reset()         { *m = GetCustomObjectRequest{} }
func (m *GetCustomObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomObjectRequest) ProtoMessage()    {}
func (*GetCustomObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_05670c5187cf7604, []int{0}
}
func (m *GetCustomObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomObjectRequest.Unmarshal(m, b)
}
func (m *GetCustomObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomObjectRequest.Marshal(b, m, deterministic)
}
func (dst *GetCustomObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomObjectRequest.Merge(dst, src)
}
func (m *GetCustomObjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomObjectRequest.Size(m)
}
func (m *GetCustomObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomObjectRequest proto.InternalMessageInfo

func (m *GetCustomObjectRequest) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

type DeleteCustomObjectRequest struct {
	ObjId                string   `protobuf:"bytes,1,opt,name=objId,proto3" json:"objId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomObjectRequest) Reset()         { *m = DeleteCustomObjectRequest{} }
func (m *DeleteCustomObjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomObjectRequest) ProtoMessage()    {}
func (*DeleteCustomObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_05670c5187cf7604, []int{1}
}
func (m *DeleteCustomObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomObjectRequest.Unmarshal(m, b)
}
func (m *DeleteCustomObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomObjectRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteCustomObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomObjectRequest.Merge(dst, src)
}
func (m *DeleteCustomObjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomObjectRequest.Size(m)
}
func (m *DeleteCustomObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomObjectRequest proto.InternalMessageInfo

func (m *DeleteCustomObjectRequest) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

type GetCustomFieldRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomFieldRequest) Reset()         { *m = GetCustomFieldRequest{} }
func (m *GetCustomFieldRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomFieldRequest) ProtoMessage()    {}
func (*GetCustomFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_05670c5187cf7604, []int{2}
}
func (m *GetCustomFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomFieldRequest.Unmarshal(m, b)
}
func (m *GetCustomFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomFieldRequest.Marshal(b, m, deterministic)
}
func (dst *GetCustomFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomFieldRequest.Merge(dst, src)
}
func (m *GetCustomFieldRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomFieldRequest.Size(m)
}
func (m *GetCustomFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomFieldRequest proto.InternalMessageInfo

func (m *GetCustomFieldRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteCustomFieldRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomFieldRequest) Reset()         { *m = DeleteCustomFieldRequest{} }
func (m *DeleteCustomFieldRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomFieldRequest) ProtoMessage()    {}
func (*DeleteCustomFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_05670c5187cf7604, []int{3}
}
func (m *DeleteCustomFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomFieldRequest.Unmarshal(m, b)
}
func (m *DeleteCustomFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomFieldRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteCustomFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomFieldRequest.Merge(dst, src)
}
func (m *DeleteCustomFieldRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomFieldRequest.Size(m)
}
func (m *DeleteCustomFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomFieldRequest proto.InternalMessageInfo

func (m *DeleteCustomFieldRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*GetCustomObjectRequest)(nil), "meta.GetCustomObjectRequest")
	proto.RegisterType((*DeleteCustomObjectRequest)(nil), "meta.DeleteCustomObjectRequest")
	proto.RegisterType((*GetCustomFieldRequest)(nil), "meta.GetCustomFieldRequest")
	proto.RegisterType((*DeleteCustomFieldRequest)(nil), "meta.DeleteCustomFieldRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomObjectServiceClient is the client API for CustomObjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomObjectServiceClient interface {
	Create(ctx context.Context, in *CustomObject, opts ...grpc.CallOption) (*CustomObject, error)
	Update(ctx context.Context, in *CustomObject, opts ...grpc.CallOption) (*CustomObject, error)
	Delete(ctx context.Context, in *DeleteCustomObjectRequest, opts ...grpc.CallOption) (*CustomObject, error)
	Get(ctx context.Context, in *GetCustomObjectRequest, opts ...grpc.CallOption) (*CustomObject, error)
}

type customObjectServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomObjectServiceClient(cc *grpc.ClientConn) CustomObjectServiceClient {
	return &customObjectServiceClient{cc}
}

func (c *customObjectServiceClient) Create(ctx context.Context, in *CustomObject, opts ...grpc.CallOption) (*CustomObject, error) {
	out := new(CustomObject)
	err := c.cc.Invoke(ctx, "/meta.CustomObjectService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customObjectServiceClient) Update(ctx context.Context, in *CustomObject, opts ...grpc.CallOption) (*CustomObject, error) {
	out := new(CustomObject)
	err := c.cc.Invoke(ctx, "/meta.CustomObjectService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customObjectServiceClient) Delete(ctx context.Context, in *DeleteCustomObjectRequest, opts ...grpc.CallOption) (*CustomObject, error) {
	out := new(CustomObject)
	err := c.cc.Invoke(ctx, "/meta.CustomObjectService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customObjectServiceClient) Get(ctx context.Context, in *GetCustomObjectRequest, opts ...grpc.CallOption) (*CustomObject, error) {
	out := new(CustomObject)
	err := c.cc.Invoke(ctx, "/meta.CustomObjectService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomObjectServiceServer is the server API for CustomObjectService service.
type CustomObjectServiceServer interface {
	Create(context.Context, *CustomObject) (*CustomObject, error)
	Update(context.Context, *CustomObject) (*CustomObject, error)
	Delete(context.Context, *DeleteCustomObjectRequest) (*CustomObject, error)
	Get(context.Context, *GetCustomObjectRequest) (*CustomObject, error)
}

func RegisterCustomObjectServiceServer(s *grpc.Server, srv CustomObjectServiceServer) {
	s.RegisterService(&_CustomObjectService_serviceDesc, srv)
}

func _CustomObjectService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomObjectServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomObjectService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomObjectServiceServer).Create(ctx, req.(*CustomObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomObjectService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomObjectServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomObjectService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomObjectServiceServer).Update(ctx, req.(*CustomObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomObjectService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCustomObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomObjectServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomObjectService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomObjectServiceServer).Delete(ctx, req.(*DeleteCustomObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomObjectService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomObjectServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomObjectService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomObjectServiceServer).Get(ctx, req.(*GetCustomObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomObjectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "meta.CustomObjectService",
	HandlerType: (*CustomObjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CustomObjectService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CustomObjectService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CustomObjectService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CustomObjectService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/meta/meta.proto",
}

// CustomFieldServiceClient is the client API for CustomFieldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomFieldServiceClient interface {
	Create(ctx context.Context, in *CustomField, opts ...grpc.CallOption) (*CustomField, error)
	Update(ctx context.Context, in *CustomField, opts ...grpc.CallOption) (*CustomField, error)
	Get(ctx context.Context, in *GetCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error)
	Delete(ctx context.Context, in *DeleteCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error)
}

type customFieldServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomFieldServiceClient(cc *grpc.ClientConn) CustomFieldServiceClient {
	return &customFieldServiceClient{cc}
}

func (c *customFieldServiceClient) Create(ctx context.Context, in *CustomField, opts ...grpc.CallOption) (*CustomField, error) {
	out := new(CustomField)
	err := c.cc.Invoke(ctx, "/meta.CustomFieldService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customFieldServiceClient) Update(ctx context.Context, in *CustomField, opts ...grpc.CallOption) (*CustomField, error) {
	out := new(CustomField)
	err := c.cc.Invoke(ctx, "/meta.CustomFieldService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customFieldServiceClient) Get(ctx context.Context, in *GetCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error) {
	out := new(CustomField)
	err := c.cc.Invoke(ctx, "/meta.CustomFieldService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customFieldServiceClient) Delete(ctx context.Context, in *DeleteCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error) {
	out := new(CustomField)
	err := c.cc.Invoke(ctx, "/meta.CustomFieldService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomFieldServiceServer is the server API for CustomFieldService service.
type CustomFieldServiceServer interface {
	Create(context.Context, *CustomField) (*CustomField, error)
	Update(context.Context, *CustomField) (*CustomField, error)
	Get(context.Context, *GetCustomFieldRequest) (*CustomField, error)
	Delete(context.Context, *DeleteCustomFieldRequest) (*CustomField, error)
}

func RegisterCustomFieldServiceServer(s *grpc.Server, srv CustomFieldServiceServer) {
	s.RegisterService(&_CustomFieldService_serviceDesc, srv)
}

func _CustomFieldService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomField)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFieldServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomFieldService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFieldServiceServer).Create(ctx, req.(*CustomField))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomFieldService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomField)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFieldServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomFieldService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFieldServiceServer).Update(ctx, req.(*CustomField))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomFieldService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFieldServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomFieldService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFieldServiceServer).Get(ctx, req.(*GetCustomFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomFieldService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCustomFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFieldServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomFieldService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFieldServiceServer).Delete(ctx, req.(*DeleteCustomFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomFieldService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "meta.CustomFieldService",
	HandlerType: (*CustomFieldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CustomFieldService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CustomFieldService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CustomFieldService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CustomFieldService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/meta/meta.proto",
}

func init() { proto.RegisterFile("proto/meta/meta.proto", fileDescriptor_meta_05670c5187cf7604) }

var fileDescriptor_meta_05670c5187cf7604 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x49, 0x04, 0x13, 0x7a, 0x60, 0xbe, 0x10, 0x0b, 0x88, 0x2d, 0x65,
	0x9c, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x9f, 0x94, 0x95, 0x96,
	0x5f, 0x94, 0x9c, 0x8a, 0x60, 0x20, 0xe9, 0x2c, 0xa9, 0x2c, 0x48, 0x2d, 0x86, 0x68, 0x55, 0xd2,
	0xe3, 0x12, 0x73, 0x4f, 0x2d, 0x71, 0x2e, 0x2d, 0x2e, 0xc9, 0xcf, 0xf5, 0x4f, 0xca, 0x4a, 0x4d,
	0x2e, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0xcd, 0x4f, 0xca, 0xf2,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0x0c, 0xb9, 0x24, 0x5d, 0x52,
	0x73, 0x52, 0x4b, 0x52, 0x89, 0xd7, 0xa2, 0xce, 0x25, 0x0a, 0xb7, 0xc2, 0x2d, 0x33, 0x35, 0x27,
	0x05, 0xa6, 0x9c, 0x8f, 0x8b, 0x29, 0x13, 0xa6, 0x96, 0x29, 0x33, 0x45, 0x49, 0x8b, 0x4b, 0x02,
	0xd9, 0x6c, 0x7c, 0x6a, 0x8d, 0x7e, 0x32, 0x72, 0x09, 0x23, 0x3b, 0x21, 0x38, 0xb5, 0xa8, 0x2c,
	0x33, 0x39, 0x55, 0xc8, 0x88, 0x8b, 0xcd, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x55, 0x48, 0x48, 0x0f,
	0x1c, 0x42, 0xc8, 0x8a, 0xa4, 0xb0, 0x88, 0x29, 0x31, 0x80, 0xf4, 0x84, 0x16, 0xa4, 0x90, 0xa6,
	0xc7, 0x9e, 0x8b, 0x0d, 0xe2, 0x56, 0x21, 0x79, 0x88, 0x3c, 0xce, 0x50, 0xc1, 0x61, 0x80, 0x25,
	0x17, 0xb3, 0x7b, 0x6a, 0x89, 0x90, 0x0c, 0x44, 0x12, 0x7b, 0x1c, 0x60, 0xd7, 0x6a, 0xf4, 0x81,
	0x91, 0x4b, 0x08, 0x29, 0x88, 0x60, 0x5e, 0x37, 0x80, 0x7b, 0x5d, 0x10, 0x59, 0x1b, 0x58, 0x8d,
	0x14, 0xa6, 0x90, 0x12, 0x03, 0x48, 0x07, 0xd4, 0xe3, 0xc4, 0xea, 0x30, 0x87, 0xb8, 0x5a, 0x1a,
	0xcd, 0xd5, 0xc8, 0x51, 0x85, 0x5d, 0xa3, 0x2d, 0x3c, 0xbc, 0xe4, 0x30, 0xc3, 0x8b, 0xa0, 0x76,
	0x27, 0xbd, 0x28, 0x1d, 0x22, 0x53, 0xb7, 0x35, 0x88, 0x48, 0x62, 0x03, 0x0b, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x96, 0x29, 0x4c, 0xb8, 0x31, 0x03, 0x00, 0x00,
}
