// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/meta/meta.proto

package meta

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetCustomObjectRequest) Validate() error {
	return nil
}
func (this *DeleteCustomObjectRequest) Validate() error {
	return nil
}
func (this *GetCustomFieldRequest) Validate() error {
	return nil
}
func (this *DeleteCustomFieldRequest) Validate() error {
	return nil
}
