// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/meta/meta.proto

package meta // import "github.com/objforce/objforce/proto/meta"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import emptypb "google.golang.org/protobuf/types/known/emptypb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateCustomObjectRequest struct {
	OrgId                string           `protobuf:"bytes,2,opt,name=orgId,proto3" json:"orgId,omitempty"`
	ObjName              string           `protobuf:"bytes,3,opt,name=objName,proto3" json:"objName,omitempty"`
	DeploymentStatus     DeploymentStatus `protobuf:"varint,15,opt,name=DeploymentStatus,proto3,enum=meta.DeploymentStatus" json:"DeploymentStatus,omitempty"`
	Deprecated           bool             `protobuf:"varint,16,opt,name=Deprecated,proto3" json:"Deprecated,omitempty"`
	Description          string           `protobuf:"bytes,17,opt,name=Description,proto3" json:"Description,omitempty"`
	EnableBulkApi        bool             `protobuf:"varint,19,opt,name=enableBulkApi,proto3" json:"enableBulkApi,omitempty"`
	ExternalDataSource   string           `protobuf:"bytes,29,opt,name=externalDataSource,proto3" json:"externalDataSource,omitempty"`
	ExternalName         string           `protobuf:"bytes,30,opt,name=externalName,proto3" json:"externalName,omitempty"`
	Fields               []*CustomField   `protobuf:"bytes,33,rep,name=fields,proto3" json:"fields,omitempty"`
	Indexes              []*Index         `protobuf:"bytes,38,rep,name=indexes,proto3" json:"indexes,omitempty"`
	Label                string           `protobuf:"bytes,39,opt,name=Label,proto3" json:"Label,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateCustomObjectRequest) Reset()         { *m = CreateCustomObjectRequest{} }
func (m *CreateCustomObjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomObjectRequest) ProtoMessage()    {}
func (*CreateCustomObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_039d73731e690bd9, []int{0}
}
func (m *CreateCustomObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomObjectRequest.Unmarshal(m, b)
}
func (m *CreateCustomObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomObjectRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCustomObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomObjectRequest.Merge(dst, src)
}
func (m *CreateCustomObjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomObjectRequest.Size(m)
}
func (m *CreateCustomObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomObjectRequest proto.InternalMessageInfo

func (m *CreateCustomObjectRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *CreateCustomObjectRequest) GetObjName() string {
	if m != nil {
		return m.ObjName
	}
	return ""
}

func (m *CreateCustomObjectRequest) GetDeploymentStatus() DeploymentStatus {
	if m != nil {
		return m.DeploymentStatus
	}
	return DeploymentStatus_InDevelopment
}

func (m *CreateCustomObjectRequest) GetDeprecated() bool {
	if m != nil {
		return m.Deprecated
	}
	return false
}

func (m *CreateCustomObjectRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateCustomObjectRequest) GetEnableBulkApi() bool {
	if m != nil {
		return m.EnableBulkApi
	}
	return false
}

func (m *CreateCustomObjectRequest) GetExternalDataSource() string {
	if m != nil {
		return m.ExternalDataSource
	}
	return ""
}

func (m *CreateCustomObjectRequest) GetExternalName() string {
	if m != nil {
		return m.ExternalName
	}
	return ""
}

func (m *CreateCustomObjectRequest) GetFields() []*CustomField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *CreateCustomObjectRequest) GetIndexes() []*Index {
	if m != nil {
		return m.Indexes
	}
	return nil
}

func (m *CreateCustomObjectRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type FindByObjNameRequest struct {
	OrgId                string   `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	ObjName              string   `protobuf:"bytes,2,opt,name=objName,proto3" json:"objName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByObjNameRequest) Reset()         { *m = FindByObjNameRequest{} }
func (m *FindByObjNameRequest) String() string { return proto.CompactTextString(m) }
func (*FindByObjNameRequest) ProtoMessage()    {}
func (*FindByObjNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_039d73731e690bd9, []int{1}
}
func (m *FindByObjNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByObjNameRequest.Unmarshal(m, b)
}
func (m *FindByObjNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByObjNameRequest.Marshal(b, m, deterministic)
}
func (dst *FindByObjNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByObjNameRequest.Merge(dst, src)
}
func (m *FindByObjNameRequest) XXX_Size() int {
	return xxx_messageInfo_FindByObjNameRequest.Size(m)
}
func (m *FindByObjNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByObjNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByObjNameRequest proto.InternalMessageInfo

func (m *FindByObjNameRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *FindByObjNameRequest) GetObjName() string {
	if m != nil {
		return m.ObjName
	}
	return ""
}

type GetCustomObjectRequest struct {
	ObjId                string   `protobuf:"bytes,1,opt,name=objId,proto3" json:"objId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomObjectRequest) Reset()         { *m = GetCustomObjectRequest{} }
func (m *GetCustomObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomObjectRequest) ProtoMessage()    {}
func (*GetCustomObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_039d73731e690bd9, []int{2}
}
func (m *GetCustomObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomObjectRequest.Unmarshal(m, b)
}
func (m *GetCustomObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomObjectRequest.Marshal(b, m, deterministic)
}
func (dst *GetCustomObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomObjectRequest.Merge(dst, src)
}
func (m *GetCustomObjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomObjectRequest.Size(m)
}
func (m *GetCustomObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomObjectRequest proto.InternalMessageInfo

func (m *GetCustomObjectRequest) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

type DeleteCustomObjectRequest struct {
	ObjId                string   `protobuf:"bytes,1,opt,name=objId,proto3" json:"objId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomObjectRequest) Reset()         { *m = DeleteCustomObjectRequest{} }
func (m *DeleteCustomObjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomObjectRequest) ProtoMessage()    {}
func (*DeleteCustomObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_039d73731e690bd9, []int{3}
}
func (m *DeleteCustomObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomObjectRequest.Unmarshal(m, b)
}
func (m *DeleteCustomObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomObjectRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteCustomObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomObjectRequest.Merge(dst, src)
}
func (m *DeleteCustomObjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomObjectRequest.Size(m)
}
func (m *DeleteCustomObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomObjectRequest proto.InternalMessageInfo

func (m *DeleteCustomObjectRequest) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

type GetCustomFieldRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomFieldRequest) Reset()         { *m = GetCustomFieldRequest{} }
func (m *GetCustomFieldRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomFieldRequest) ProtoMessage()    {}
func (*GetCustomFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_039d73731e690bd9, []int{4}
}
func (m *GetCustomFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomFieldRequest.Unmarshal(m, b)
}
func (m *GetCustomFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomFieldRequest.Marshal(b, m, deterministic)
}
func (dst *GetCustomFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomFieldRequest.Merge(dst, src)
}
func (m *GetCustomFieldRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomFieldRequest.Size(m)
}
func (m *GetCustomFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomFieldRequest proto.InternalMessageInfo

func (m *GetCustomFieldRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteCustomFieldRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomFieldRequest) Reset()         { *m = DeleteCustomFieldRequest{} }
func (m *DeleteCustomFieldRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomFieldRequest) ProtoMessage()    {}
func (*DeleteCustomFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_039d73731e690bd9, []int{5}
}
func (m *DeleteCustomFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomFieldRequest.Unmarshal(m, b)
}
func (m *DeleteCustomFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomFieldRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteCustomFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomFieldRequest.Merge(dst, src)
}
func (m *DeleteCustomFieldRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomFieldRequest.Size(m)
}
func (m *DeleteCustomFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomFieldRequest proto.InternalMessageInfo

func (m *DeleteCustomFieldRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateCustomObjectRequest)(nil), "meta.CreateCustomObjectRequest")
	proto.RegisterType((*FindByObjNameRequest)(nil), "meta.FindByObjNameRequest")
	proto.RegisterType((*GetCustomObjectRequest)(nil), "meta.GetCustomObjectRequest")
	proto.RegisterType((*DeleteCustomObjectRequest)(nil), "meta.DeleteCustomObjectRequest")
	proto.RegisterType((*GetCustomFieldRequest)(nil), "meta.GetCustomFieldRequest")
	proto.RegisterType((*DeleteCustomFieldRequest)(nil), "meta.DeleteCustomFieldRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomObjectServiceClient is the client API for CustomObjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomObjectServiceClient interface {
	Create(ctx context.Context, in *CreateCustomObjectRequest, opts ...grpc.CallOption) (*CustomObject, error)
	Retrieve(ctx context.Context, in *GetCustomObjectRequest, opts ...grpc.CallOption) (*CustomObject, error)
	Update(ctx context.Context, in *CustomObject, opts ...grpc.CallOption) (*CustomObject, error)
	Delete(ctx context.Context, in *DeleteCustomObjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	FindByObjName(ctx context.Context, in *FindByObjNameRequest, opts ...grpc.CallOption) (*CustomObject, error)
}

type customObjectServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomObjectServiceClient(cc *grpc.ClientConn) CustomObjectServiceClient {
	return &customObjectServiceClient{cc}
}

func (c *customObjectServiceClient) Create(ctx context.Context, in *CreateCustomObjectRequest, opts ...grpc.CallOption) (*CustomObject, error) {
	out := new(CustomObject)
	err := c.cc.Invoke(ctx, "/meta.CustomObjectService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customObjectServiceClient) Retrieve(ctx context.Context, in *GetCustomObjectRequest, opts ...grpc.CallOption) (*CustomObject, error) {
	out := new(CustomObject)
	err := c.cc.Invoke(ctx, "/meta.CustomObjectService/Retrieve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customObjectServiceClient) Update(ctx context.Context, in *CustomObject, opts ...grpc.CallOption) (*CustomObject, error) {
	out := new(CustomObject)
	err := c.cc.Invoke(ctx, "/meta.CustomObjectService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customObjectServiceClient) Delete(ctx context.Context, in *DeleteCustomObjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/meta.CustomObjectService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customObjectServiceClient) FindByObjName(ctx context.Context, in *FindByObjNameRequest, opts ...grpc.CallOption) (*CustomObject, error) {
	out := new(CustomObject)
	err := c.cc.Invoke(ctx, "/meta.CustomObjectService/FindByObjName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomObjectServiceServer is the server API for CustomObjectService service.
type CustomObjectServiceServer interface {
	Create(context.Context, *CreateCustomObjectRequest) (*CustomObject, error)
	Retrieve(context.Context, *GetCustomObjectRequest) (*CustomObject, error)
	Update(context.Context, *CustomObject) (*CustomObject, error)
	Delete(context.Context, *DeleteCustomObjectRequest) (*emptypb.Empty, error)
	FindByObjName(context.Context, *FindByObjNameRequest) (*CustomObject, error)
}

func RegisterCustomObjectServiceServer(s *grpc.Server, srv CustomObjectServiceServer) {
	s.RegisterService(&_CustomObjectService_serviceDesc, srv)
}

func _CustomObjectService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomObjectServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomObjectService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomObjectServiceServer).Create(ctx, req.(*CreateCustomObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomObjectService_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomObjectServiceServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomObjectService/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomObjectServiceServer).Retrieve(ctx, req.(*GetCustomObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomObjectService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomObjectServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomObjectService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomObjectServiceServer).Update(ctx, req.(*CustomObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomObjectService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCustomObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomObjectServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomObjectService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomObjectServiceServer).Delete(ctx, req.(*DeleteCustomObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomObjectService_FindByObjName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByObjNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomObjectServiceServer).FindByObjName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomObjectService/FindByObjName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomObjectServiceServer).FindByObjName(ctx, req.(*FindByObjNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomObjectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "meta.CustomObjectService",
	HandlerType: (*CustomObjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CustomObjectService_Create_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _CustomObjectService_Retrieve_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CustomObjectService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CustomObjectService_Delete_Handler,
		},
		{
			MethodName: "FindByObjName",
			Handler:    _CustomObjectService_FindByObjName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/meta/meta.proto",
}

// CustomFieldServiceClient is the client API for CustomFieldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomFieldServiceClient interface {
	Create(ctx context.Context, in *CustomField, opts ...grpc.CallOption) (*CustomField, error)
	Update(ctx context.Context, in *CustomField, opts ...grpc.CallOption) (*CustomField, error)
	Get(ctx context.Context, in *GetCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error)
	Delete(ctx context.Context, in *DeleteCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error)
}

type customFieldServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomFieldServiceClient(cc *grpc.ClientConn) CustomFieldServiceClient {
	return &customFieldServiceClient{cc}
}

func (c *customFieldServiceClient) Create(ctx context.Context, in *CustomField, opts ...grpc.CallOption) (*CustomField, error) {
	out := new(CustomField)
	err := c.cc.Invoke(ctx, "/meta.CustomFieldService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customFieldServiceClient) Update(ctx context.Context, in *CustomField, opts ...grpc.CallOption) (*CustomField, error) {
	out := new(CustomField)
	err := c.cc.Invoke(ctx, "/meta.CustomFieldService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customFieldServiceClient) Get(ctx context.Context, in *GetCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error) {
	out := new(CustomField)
	err := c.cc.Invoke(ctx, "/meta.CustomFieldService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customFieldServiceClient) Delete(ctx context.Context, in *DeleteCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error) {
	out := new(CustomField)
	err := c.cc.Invoke(ctx, "/meta.CustomFieldService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomFieldServiceServer is the server API for CustomFieldService service.
type CustomFieldServiceServer interface {
	Create(context.Context, *CustomField) (*CustomField, error)
	Update(context.Context, *CustomField) (*CustomField, error)
	Get(context.Context, *GetCustomFieldRequest) (*CustomField, error)
	Delete(context.Context, *DeleteCustomFieldRequest) (*CustomField, error)
}

func RegisterCustomFieldServiceServer(s *grpc.Server, srv CustomFieldServiceServer) {
	s.RegisterService(&_CustomFieldService_serviceDesc, srv)
}

func _CustomFieldService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomField)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFieldServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomFieldService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFieldServiceServer).Create(ctx, req.(*CustomField))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomFieldService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomField)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFieldServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomFieldService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFieldServiceServer).Update(ctx, req.(*CustomField))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomFieldService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFieldServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomFieldService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFieldServiceServer).Get(ctx, req.(*GetCustomFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomFieldService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCustomFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFieldServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.CustomFieldService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFieldServiceServer).Delete(ctx, req.(*DeleteCustomFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomFieldService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "meta.CustomFieldService",
	HandlerType: (*CustomFieldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CustomFieldService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CustomFieldService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CustomFieldService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CustomFieldService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/meta/meta.proto",
}

func init() { proto.RegisterFile("proto/meta/meta.proto", fileDescriptor_meta_039d73731e690bd9) }

var fileDescriptor_meta_039d73731e690bd9 = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xcd, 0x05, 0xd2, 0x32, 0xa1, 0xa5, 0xdd, 0xb6, 0xd1, 0xd6, 0x85, 0x10, 0x2c, 0xa0, 0x01,
	0x21, 0x07, 0xd2, 0x07, 0x1e, 0x10, 0xa0, 0x26, 0x21, 0x55, 0x25, 0x44, 0x25, 0x47, 0xbc, 0xf0,
	0xe6, 0xcb, 0x24, 0x38, 0xd8, 0x5e, 0x63, 0xaf, 0xab, 0xe6, 0xbb, 0xf8, 0x13, 0xbe, 0x84, 0x4f,
	0x40, 0xde, 0x8d, 0x83, 0x53, 0xdb, 0xb4, 0x2f, 0xd6, 0xce, 0x99, 0x73, 0xc6, 0xb3, 0x67, 0x46,
	0x0b, 0x07, 0x41, 0xc8, 0x38, 0xeb, 0x79, 0xc8, 0x0d, 0xf1, 0xd1, 0x44, 0x4c, 0xee, 0x24, 0x67,
	0xe5, 0x68, 0xc6, 0xd8, 0xcc, 0xc5, 0x9e, 0xc0, 0xcc, 0x78, 0xda, 0x43, 0x2f, 0xe0, 0x0b, 0x49,
	0x51, 0x4e, 0x66, 0x0e, 0xff, 0x1e, 0x9b, 0x9a, 0xc5, 0xbc, 0x1e, 0x33, 0xe7, 0x53, 0x16, 0x5a,
	0xf8, 0xef, 0x90, 0x29, 0xcb, 0x17, 0x01, 0x46, 0x52, 0xa4, 0xfe, 0xaa, 0xc3, 0xe1, 0x30, 0x44,
	0x83, 0xe3, 0x30, 0x8e, 0x38, 0xf3, 0x2e, 0xcc, 0x39, 0x5a, 0x5c, 0xc7, 0x9f, 0x31, 0x46, 0x9c,
	0xec, 0xc3, 0x5d, 0x16, 0xce, 0xce, 0x6d, 0x5a, 0xeb, 0x54, 0xbb, 0xf7, 0x74, 0x19, 0x10, 0x0a,
	0x1b, 0xcc, 0x9c, 0x7f, 0x31, 0x3c, 0xa4, 0x75, 0x81, 0xa7, 0x21, 0x19, 0xc0, 0xce, 0x08, 0x03,
	0x97, 0x2d, 0x3c, 0xf4, 0xf9, 0x84, 0x1b, 0x3c, 0x8e, 0xe8, 0x83, 0x4e, 0xb5, 0xbb, 0xdd, 0x6f,
	0x69, 0xe2, 0x32, 0xd7, 0xb3, 0x7a, 0x8e, 0x4f, 0xda, 0x00, 0x23, 0x0c, 0x42, 0xb4, 0x0c, 0x8e,
	0x36, 0xdd, 0xe9, 0x54, 0xbb, 0x9b, 0x7a, 0x06, 0x21, 0x1d, 0x68, 0x8e, 0x30, 0xb2, 0x42, 0x27,
	0xe0, 0x0e, 0xf3, 0xe9, 0xae, 0xe8, 0x20, 0x0b, 0x91, 0xa7, 0xb0, 0x85, 0xbe, 0x61, 0xba, 0x38,
	0x88, 0xdd, 0x1f, 0xa7, 0x81, 0x43, 0xf7, 0x44, 0x91, 0x75, 0x90, 0x68, 0x40, 0xf0, 0x8a, 0x63,
	0xe8, 0x1b, 0xee, 0xc8, 0xe0, 0xc6, 0x84, 0xc5, 0xa1, 0x85, 0xf4, 0x91, 0x28, 0x57, 0x90, 0x21,
	0x2a, 0xdc, 0x4f, 0x51, 0x71, 0xf5, 0xb6, 0x60, 0xae, 0x61, 0xe4, 0x05, 0x34, 0xa6, 0x0e, 0xba,
	0x76, 0x44, 0x9f, 0x74, 0xea, 0xdd, 0x66, 0x7f, 0x57, 0xde, 0x5a, 0x5a, 0x3b, 0x4e, 0x32, 0xfa,
	0x92, 0x40, 0x9e, 0xc1, 0x86, 0xe3, 0xdb, 0x78, 0x85, 0x11, 0x7d, 0x2e, 0xb8, 0x4d, 0xc9, 0x3d,
	0x4f, 0x40, 0x3d, 0xcd, 0x25, 0x13, 0xf8, 0x6c, 0x98, 0xe8, 0xd2, 0x63, 0x39, 0x01, 0x11, 0xa8,
	0x63, 0xd8, 0x1f, 0x3b, 0xbe, 0x3d, 0x58, 0x5c, 0x48, 0xe3, 0x73, 0xf3, 0xaa, 0x96, 0xcc, 0xab,
	0xb6, 0x36, 0x2f, 0x55, 0x83, 0xd6, 0x19, 0xf2, 0xb2, 0xc9, 0x9b, 0xf3, 0x4c, 0xa5, 0x24, 0x50,
	0xdf, 0xc0, 0xe1, 0x08, 0x5d, 0x2c, 0x5f, 0x96, 0xbc, 0xe4, 0x18, 0x0e, 0x56, 0xbf, 0x90, 0x0e,
	0x2c, 0xe9, 0xdb, 0x50, 0x73, 0x52, 0x6e, 0xcd, 0xb1, 0xd5, 0x97, 0x40, 0xb3, 0xb5, 0xff, 0xc7,
	0xed, 0xff, 0xae, 0xc1, 0x5e, 0xb6, 0x85, 0x09, 0x86, 0x97, 0x8e, 0x85, 0xe4, 0x23, 0x34, 0xe4,
	0x32, 0x93, 0xc7, 0x4b, 0xe7, 0xcb, 0x56, 0x5b, 0x21, 0xd9, 0xd1, 0xc8, 0x94, 0x5a, 0x21, 0x1f,
	0x60, 0x53, 0x47, 0x1e, 0x3a, 0x78, 0x89, 0xe4, 0xa1, 0x64, 0x14, 0x1b, 0x54, 0xa2, 0xef, 0x43,
	0xe3, 0x6b, 0x60, 0x27, 0x0d, 0x14, 0xe4, 0x4b, 0x34, 0x43, 0x68, 0xc8, 0x8b, 0xa7, 0x4d, 0x97,
	0x5a, 0xac, 0xb4, 0x34, 0xf9, 0x00, 0x68, 0xe9, 0x03, 0xa0, 0x7d, 0x4a, 0x1e, 0x00, 0xb5, 0x42,
	0x4e, 0x61, 0x6b, 0x6d, 0x23, 0x88, 0x22, 0x6b, 0x15, 0xad, 0x49, 0x71, 0x1f, 0xfd, 0x3f, 0x55,
	0x20, 0x19, 0xef, 0x53, 0x4f, 0x5f, 0xaf, 0x3c, 0xcd, 0x6f, 0xb3, 0x92, 0x87, 0xd4, 0x4a, 0xa2,
	0x58, 0x9a, 0x70, 0x5b, 0xc5, 0x5b, 0xa8, 0x9f, 0x21, 0x27, 0x47, 0xd7, 0x1c, 0xcf, 0xee, 0x40,
	0xb1, 0xf0, 0xfd, 0xca, 0xbb, 0x76, 0xde, 0xbb, 0x1b, 0xe5, 0x03, 0xed, 0xdb, 0xab, 0x5b, 0x3e,
	0x9a, 0xef, 0x92, 0x8f, 0xd9, 0x10, 0xc0, 0xc9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xce, 0x71,
	0x3a, 0xcb, 0xa5, 0x05, 0x00, 0x00,
}
