// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package meta

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindCustomObjectRequest struct {
	ObjId                string   `protobuf:"bytes,1,opt,name=objId,proto3" json:"objId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindCustomObjectRequest) Reset()         { *m = FindCustomObjectRequest{} }
func (m *FindCustomObjectRequest) String() string { return proto.CompactTextString(m) }
func (*FindCustomObjectRequest) ProtoMessage()    {}
func (*FindCustomObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}

func (m *FindCustomObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindCustomObjectRequest.Unmarshal(m, b)
}
func (m *FindCustomObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindCustomObjectRequest.Marshal(b, m, deterministic)
}
func (m *FindCustomObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindCustomObjectRequest.Merge(m, src)
}
func (m *FindCustomObjectRequest) XXX_Size() int {
	return xxx_messageInfo_FindCustomObjectRequest.Size(m)
}
func (m *FindCustomObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindCustomObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindCustomObjectRequest proto.InternalMessageInfo

func (m *FindCustomObjectRequest) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

type OrgAndObjTypeRequest struct {
	OrgId                string   `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	ObjType              string   `protobuf:"bytes,2,opt,name=objType,proto3" json:"objType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrgAndObjTypeRequest) Reset()         { *m = OrgAndObjTypeRequest{} }
func (m *OrgAndObjTypeRequest) String() string { return proto.CompactTextString(m) }
func (*OrgAndObjTypeRequest) ProtoMessage()    {}
func (*OrgAndObjTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{1}
}

func (m *OrgAndObjTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgAndObjTypeRequest.Unmarshal(m, b)
}
func (m *OrgAndObjTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgAndObjTypeRequest.Marshal(b, m, deterministic)
}
func (m *OrgAndObjTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgAndObjTypeRequest.Merge(m, src)
}
func (m *OrgAndObjTypeRequest) XXX_Size() int {
	return xxx_messageInfo_OrgAndObjTypeRequest.Size(m)
}
func (m *OrgAndObjTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgAndObjTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrgAndObjTypeRequest proto.InternalMessageInfo

func (m *OrgAndObjTypeRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *OrgAndObjTypeRequest) GetObjType() string {
	if m != nil {
		return m.ObjType
	}
	return ""
}

type DeleteCustomObjectRequest struct {
	ObjId                string   `protobuf:"bytes,1,opt,name=objId,proto3" json:"objId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomObjectRequest) Reset()         { *m = DeleteCustomObjectRequest{} }
func (m *DeleteCustomObjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomObjectRequest) ProtoMessage()    {}
func (*DeleteCustomObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{2}
}

func (m *DeleteCustomObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomObjectRequest.Unmarshal(m, b)
}
func (m *DeleteCustomObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomObjectRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCustomObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomObjectRequest.Merge(m, src)
}
func (m *DeleteCustomObjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomObjectRequest.Size(m)
}
func (m *DeleteCustomObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomObjectRequest proto.InternalMessageInfo

func (m *DeleteCustomObjectRequest) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

type FindCustomFieldRequest struct {
	FieldId              string   `protobuf:"bytes,1,opt,name=fieldId,proto3" json:"fieldId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindCustomFieldRequest) Reset()         { *m = FindCustomFieldRequest{} }
func (m *FindCustomFieldRequest) String() string { return proto.CompactTextString(m) }
func (*FindCustomFieldRequest) ProtoMessage()    {}
func (*FindCustomFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{3}
}

func (m *FindCustomFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindCustomFieldRequest.Unmarshal(m, b)
}
func (m *FindCustomFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindCustomFieldRequest.Marshal(b, m, deterministic)
}
func (m *FindCustomFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindCustomFieldRequest.Merge(m, src)
}
func (m *FindCustomFieldRequest) XXX_Size() int {
	return xxx_messageInfo_FindCustomFieldRequest.Size(m)
}
func (m *FindCustomFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindCustomFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindCustomFieldRequest proto.InternalMessageInfo

func (m *FindCustomFieldRequest) GetFieldId() string {
	if m != nil {
		return m.FieldId
	}
	return ""
}

type DeleteCustomFieldRequest struct {
	FieldId              string   `protobuf:"bytes,1,opt,name=fieldId,proto3" json:"fieldId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomFieldRequest) Reset()         { *m = DeleteCustomFieldRequest{} }
func (m *DeleteCustomFieldRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomFieldRequest) ProtoMessage()    {}
func (*DeleteCustomFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{4}
}

func (m *DeleteCustomFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomFieldRequest.Unmarshal(m, b)
}
func (m *DeleteCustomFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomFieldRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCustomFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomFieldRequest.Merge(m, src)
}
func (m *DeleteCustomFieldRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomFieldRequest.Size(m)
}
func (m *DeleteCustomFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomFieldRequest proto.InternalMessageInfo

func (m *DeleteCustomFieldRequest) GetFieldId() string {
	if m != nil {
		return m.FieldId
	}
	return ""
}

func init() {
	proto.RegisterType((*FindCustomObjectRequest)(nil), "meta.FindCustomObjectRequest")
	proto.RegisterType((*OrgAndObjTypeRequest)(nil), "meta.OrgAndObjTypeRequest")
	proto.RegisterType((*DeleteCustomObjectRequest)(nil), "meta.DeleteCustomObjectRequest")
	proto.RegisterType((*FindCustomFieldRequest)(nil), "meta.FindCustomFieldRequest")
	proto.RegisterType((*DeleteCustomFieldRequest)(nil), "meta.DeleteCustomFieldRequest")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_3b5ea8fe65782bcc) }

var fileDescriptor_3b5ea8fe65782bcc = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x4f, 0xb3, 0x40,
	0x10, 0xc6, 0x81, 0xbc, 0x2f, 0xd5, 0xf1, 0xe4, 0xda, 0x28, 0x92, 0xfa, 0x27, 0x7b, 0xf2, 0x54,
	0x15, 0xbd, 0x1a, 0x63, 0x6b, 0x48, 0x3c, 0x61, 0x50, 0x2f, 0xde, 0x4a, 0x19, 0x1b, 0x48, 0x5b,
	0x70, 0xd9, 0x36, 0xe1, 0x63, 0xfa, 0x65, 0x3c, 0x9b, 0x65, 0xa5, 0x6e, 0x5a, 0x36, 0xe2, 0x8d,
	0x67, 0x78, 0x7e, 0x33, 0xcb, 0x33, 0x0b, 0xc0, 0x0c, 0xf9, 0xa8, 0x9f, 0xb3, 0x8c, 0x67, 0xe4,
	0x9f, 0x78, 0x76, 0x77, 0x78, 0x99, 0x63, 0x21, 0x4b, 0xf4, 0x1c, 0x0e, 0xfc, 0x64, 0x1e, 0x0f,
	0x17, 0x05, 0xcf, 0x66, 0x41, 0x94, 0xe2, 0x98, 0x87, 0xf8, 0xbe, 0xc0, 0x82, 0x93, 0x2e, 0xfc,
	0xcf, 0xa2, 0xf4, 0x21, 0x76, 0xcc, 0x53, 0xf3, 0x6c, 0x3b, 0x94, 0x82, 0xfa, 0xd0, 0x0d, 0xd8,
	0xe4, 0x6e, 0x1e, 0x07, 0x51, 0xfa, 0x5c, 0xe6, 0xa8, 0xba, 0xd9, 0x44, 0x71, 0x0b, 0x41, 0x1c,
	0xe8, 0x64, 0xd2, 0xe7, 0x58, 0x55, 0xbd, 0x96, 0xf4, 0x12, 0x0e, 0xef, 0x71, 0x8a, 0x1c, 0xdb,
	0x8f, 0xf6, 0x60, 0xff, 0xe7, 0xac, 0x7e, 0x82, 0xd3, 0xb8, 0xf6, 0x3b, 0xd0, 0x79, 0x13, 0x7a,
	0x45, 0xd4, 0x92, 0x5e, 0x83, 0xa3, 0x8e, 0x69, 0x47, 0x79, 0x1f, 0x16, 0xec, 0xa9, 0xe7, 0x7a,
	0x42, 0xb6, 0x4c, 0xc6, 0x48, 0x3c, 0xb0, 0x87, 0x0c, 0x47, 0x1c, 0x09, 0xe9, 0x57, 0xb9, 0xaa,
	0x26, 0xb7, 0xa1, 0x46, 0x0d, 0xc1, 0xbc, 0xe4, 0xf1, 0xdf, 0x98, 0x5b, 0xd8, 0x0a, 0x91, 0xb3,
	0x04, 0x97, 0x48, 0x8e, 0xa4, 0x43, 0xb3, 0x25, 0x6d, 0x03, 0x5b, 0x7e, 0x36, 0x39, 0x91, 0xef,
	0xb5, 0x59, 0x6b, 0x1a, 0x3c, 0x42, 0x6f, 0x7d, 0xe2, 0xa0, 0x94, 0x8b, 0x17, 0xeb, 0x23, 0xae,
	0xa4, 0x9a, 0xae, 0x42, 0x73, 0x47, 0xef, 0xd3, 0x04, 0xa2, 0x2c, 0xa1, 0x8e, 0xf4, 0x62, 0x15,
	0xe9, 0xae, 0x8a, 0x55, 0x1e, 0x77, 0xb3, 0x44, 0x0d, 0x41, 0x7c, 0x07, 0xda, 0x96, 0xb8, 0x51,
	0xe2, 0xec, 0xad, 0xc7, 0xa9, 0x5e, 0x09, 0x1d, 0x5e, 0x87, 0x79, 0xbc, 0x19, 0xe6, 0xaf, 0xf8,
	0xc0, 0x7a, 0x35, 0x22, 0xbb, 0xfa, 0xdb, 0xae, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x3f,
	0xaf, 0xfd, 0x8e, 0x03, 0x00, 0x00,
}
