// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package meta

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetrieveCustomObjectRequest struct {
	ObjId                string   `protobuf:"bytes,1,opt,name=objId,proto3" json:"objId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveCustomObjectRequest) Reset()         { *m = RetrieveCustomObjectRequest{} }
func (m *RetrieveCustomObjectRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveCustomObjectRequest) ProtoMessage()    {}
func (*RetrieveCustomObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}

func (m *RetrieveCustomObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveCustomObjectRequest.Unmarshal(m, b)
}
func (m *RetrieveCustomObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveCustomObjectRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveCustomObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveCustomObjectRequest.Merge(m, src)
}
func (m *RetrieveCustomObjectRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveCustomObjectRequest.Size(m)
}
func (m *RetrieveCustomObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveCustomObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveCustomObjectRequest proto.InternalMessageInfo

func (m *RetrieveCustomObjectRequest) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

type OrgAndObjTypeRequest struct {
	OrgId                string   `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	ObjType              string   `protobuf:"bytes,2,opt,name=objType,proto3" json:"objType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrgAndObjTypeRequest) Reset()         { *m = OrgAndObjTypeRequest{} }
func (m *OrgAndObjTypeRequest) String() string { return proto.CompactTextString(m) }
func (*OrgAndObjTypeRequest) ProtoMessage()    {}
func (*OrgAndObjTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{1}
}

func (m *OrgAndObjTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgAndObjTypeRequest.Unmarshal(m, b)
}
func (m *OrgAndObjTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgAndObjTypeRequest.Marshal(b, m, deterministic)
}
func (m *OrgAndObjTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgAndObjTypeRequest.Merge(m, src)
}
func (m *OrgAndObjTypeRequest) XXX_Size() int {
	return xxx_messageInfo_OrgAndObjTypeRequest.Size(m)
}
func (m *OrgAndObjTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgAndObjTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrgAndObjTypeRequest proto.InternalMessageInfo

func (m *OrgAndObjTypeRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *OrgAndObjTypeRequest) GetObjType() string {
	if m != nil {
		return m.ObjType
	}
	return ""
}

type DeleteCustomObjectRequest struct {
	ObjId                string   `protobuf:"bytes,1,opt,name=objId,proto3" json:"objId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomObjectRequest) Reset()         { *m = DeleteCustomObjectRequest{} }
func (m *DeleteCustomObjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomObjectRequest) ProtoMessage()    {}
func (*DeleteCustomObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{2}
}

func (m *DeleteCustomObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomObjectRequest.Unmarshal(m, b)
}
func (m *DeleteCustomObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomObjectRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCustomObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomObjectRequest.Merge(m, src)
}
func (m *DeleteCustomObjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomObjectRequest.Size(m)
}
func (m *DeleteCustomObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomObjectRequest proto.InternalMessageInfo

func (m *DeleteCustomObjectRequest) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

type RetrieveCustomFieldRequest struct {
	FieldId              string   `protobuf:"bytes,1,opt,name=fieldId,proto3" json:"fieldId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveCustomFieldRequest) Reset()         { *m = RetrieveCustomFieldRequest{} }
func (m *RetrieveCustomFieldRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveCustomFieldRequest) ProtoMessage()    {}
func (*RetrieveCustomFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{3}
}

func (m *RetrieveCustomFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveCustomFieldRequest.Unmarshal(m, b)
}
func (m *RetrieveCustomFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveCustomFieldRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveCustomFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveCustomFieldRequest.Merge(m, src)
}
func (m *RetrieveCustomFieldRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveCustomFieldRequest.Size(m)
}
func (m *RetrieveCustomFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveCustomFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveCustomFieldRequest proto.InternalMessageInfo

func (m *RetrieveCustomFieldRequest) GetFieldId() string {
	if m != nil {
		return m.FieldId
	}
	return ""
}

type DeleteCustomFieldRequest struct {
	FieldId              string   `protobuf:"bytes,1,opt,name=fieldId,proto3" json:"fieldId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomFieldRequest) Reset()         { *m = DeleteCustomFieldRequest{} }
func (m *DeleteCustomFieldRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomFieldRequest) ProtoMessage()    {}
func (*DeleteCustomFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{4}
}

func (m *DeleteCustomFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomFieldRequest.Unmarshal(m, b)
}
func (m *DeleteCustomFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomFieldRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCustomFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomFieldRequest.Merge(m, src)
}
func (m *DeleteCustomFieldRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomFieldRequest.Size(m)
}
func (m *DeleteCustomFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomFieldRequest proto.InternalMessageInfo

func (m *DeleteCustomFieldRequest) GetFieldId() string {
	if m != nil {
		return m.FieldId
	}
	return ""
}

func init() {
	proto.RegisterType((*RetrieveCustomObjectRequest)(nil), "meta.RetrieveCustomObjectRequest")
	proto.RegisterType((*OrgAndObjTypeRequest)(nil), "meta.OrgAndObjTypeRequest")
	proto.RegisterType((*DeleteCustomObjectRequest)(nil), "meta.DeleteCustomObjectRequest")
	proto.RegisterType((*RetrieveCustomFieldRequest)(nil), "meta.RetrieveCustomFieldRequest")
	proto.RegisterType((*DeleteCustomFieldRequest)(nil), "meta.DeleteCustomFieldRequest")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_3b5ea8fe65782bcc) }

var fileDescriptor_3b5ea8fe65782bcc = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0x81, 0x28, 0xd5, 0xf1, 0xe4, 0xda, 0x03, 0xa2, 0xd1, 0xba, 0x27, 0x4f, 0x8d, 0x52,
	0xe3, 0xcd, 0x98, 0x16, 0x43, 0xe2, 0x09, 0x83, 0x7a, 0xf1, 0x56, 0xca, 0xd8, 0x40, 0xda, 0x82,
	0xcb, 0xb6, 0x09, 0x3f, 0xd4, 0x3f, 0xe3, 0xc9, 0x2c, 0x2b, 0x64, 0x4d, 0x41, 0xdb, 0x5b, 0xe7,
	0xf5, 0x7d, 0xb3, 0xbb, 0x6f, 0x06, 0x80, 0x39, 0xf2, 0x71, 0x3f, 0x63, 0x29, 0x4f, 0xc9, 0x8e,
	0xf8, 0x6d, 0x1f, 0xf0, 0x22, 0xc3, 0x5c, 0x4a, 0x74, 0x00, 0x27, 0x01, 0x72, 0x16, 0xe3, 0x0a,
	0xdd, 0x65, 0xce, 0xd3, 0xb9, 0x1f, 0x26, 0x38, 0xe1, 0x01, 0x7e, 0x2c, 0x31, 0xe7, 0xa4, 0x0b,
	0xbb, 0x69, 0x98, 0x3c, 0x46, 0x96, 0xde, 0xd3, 0x2f, 0xf7, 0x03, 0x59, 0x50, 0x0f, 0xba, 0x3e,
	0x9b, 0x0e, 0x17, 0x91, 0x1f, 0x26, 0x2f, 0x45, 0x86, 0xaa, 0x9b, 0x4d, 0x15, 0xb7, 0x28, 0x88,
	0x05, 0x9d, 0x54, 0xfa, 0x2c, 0xa3, 0xd4, 0xab, 0x92, 0x5e, 0xc3, 0xf1, 0x03, 0xce, 0x90, 0x6f,
	0x71, 0xf4, 0x2d, 0xd8, 0xbf, 0xef, 0xeb, 0xc5, 0x38, 0x8b, 0x2a, 0xc6, 0x82, 0xce, 0xbb, 0xa8,
	0x6b, 0xaa, 0x2a, 0xe9, 0x0d, 0x58, 0xea, 0x51, 0x9b, 0x51, 0xce, 0xa7, 0x01, 0x47, 0xea, 0xdd,
	0x9e, 0x91, 0xad, 0xe2, 0x09, 0x12, 0x07, 0x4c, 0x97, 0xe1, 0x98, 0x23, 0x21, 0xfd, 0x32, 0x5f,
	0xd5, 0x64, 0x37, 0x68, 0x54, 0x13, 0xcc, 0x6b, 0x16, 0x6d, 0xc7, 0xb8, 0xb0, 0x57, 0xbd, 0x96,
	0x5c, 0x48, 0xc7, 0x1f, 0xd3, 0x6a, 0x69, 0x72, 0x0f, 0xa6, 0x7c, 0x3a, 0x39, 0x97, 0xff, 0xb7,
	0x66, 0xde, 0xd2, 0xe0, 0x09, 0x4e, 0xbd, 0x78, 0x11, 0xa9, 0xea, 0xa8, 0x90, 0x0b, 0x20, 0xc6,
	0x48, 0x6c, 0x49, 0x35, 0xad, 0x44, 0x73, 0x47, 0xe7, 0x4b, 0x07, 0xa2, 0x0c, 0xa2, 0x8a, 0xf5,
	0xaa, 0x8e, 0xf5, 0x50, 0xc5, 0x4a, 0x8f, 0xbd, 0x2e, 0x51, 0x4d, 0x10, 0x3f, 0xa1, 0x6e, 0x4a,
	0x0c, 0x95, 0x48, 0x7b, 0x4d, 0x91, 0xaa, 0xab, 0xd1, 0xdc, 0xe2, 0xae, 0x0e, 0xf4, 0x6c, 0x3d,
	0xd0, 0x7f, 0xf1, 0x91, 0xf1, 0xa6, 0x85, 0x66, 0xf9, 0xf5, 0x0d, 0xbe, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x35, 0x9b, 0x74, 0x5c, 0x9e, 0x03, 0x00, 0x00,
}
