// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types.proto

package meta

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *CustomObject) Validate() error {
	for _, item := range this.ActionOverrides {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ActionOverrides", err)
			}
		}
	}
	for _, item := range this.BusinessProcesses {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("BusinessProcesses", err)
			}
		}
	}
	for _, item := range this.CompactLayouts {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("CompactLayouts", err)
			}
		}
	}
	for _, item := range this.Fields {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Fields", err)
			}
		}
	}
	if this.FieldSets != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.FieldSets); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("FieldSets", err)
		}
	}
	if this.HistoryRetentionPolicy != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.HistoryRetentionPolicy); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("HistoryRetentionPolicy", err)
		}
	}
	for _, item := range this.Indexes {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Indexes", err)
			}
		}
	}
	for _, item := range this.ListViews {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ListViews", err)
			}
		}
	}
	for _, item := range this.NamedFilter {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("NamedFilter", err)
			}
		}
	}
	if this.NameField != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.NameField); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("NameField", err)
		}
	}
	if this.ProfileSearchLayouts != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ProfileSearchLayouts); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ProfileSearchLayouts", err)
		}
	}
	for _, item := range this.RecordTypes {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("RecordTypes", err)
			}
		}
	}
	if this.SearchLayouts != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SearchLayouts); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SearchLayouts", err)
		}
	}
	if this.SharingReasons != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SharingReasons); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SharingReasons", err)
		}
	}
	for _, item := range this.SharingRecalculations {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("SharingRecalculations", err)
			}
		}
	}
	for _, item := range this.ValidationRules {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ValidationRules", err)
			}
		}
	}
	for _, item := range this.WebLinks {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("WebLinks", err)
			}
		}
	}
	return nil
}
func (this *ActionOverride) Validate() error {
	return nil
}
func (this *BusinessProcess) Validate() error {
	for _, item := range this.Values {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Values", err)
			}
		}
	}
	return nil
}
func (this *CompactLayout) Validate() error {
	return nil
}
func (this *CustomField) Validate() error {
	for _, item := range this.SummaryFilterItems {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("SummaryFilterItems", err)
			}
		}
	}
	if this.ValueSet != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ValueSet); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ValueSet", err)
		}
	}
	return nil
}
func (this *FieldSet) Validate() error {
	for _, item := range this.AvailableFields {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("AvailableFields", err)
			}
		}
	}
	for _, item := range this.DisplayedFields {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("DisplayedFields", err)
			}
		}
	}
	return nil
}
func (this *FieldSetItem) Validate() error {
	return nil
}
func (this *HistoryRetentionPolicy) Validate() error {
	return nil
}
func (this *Index) Validate() error {
	for _, item := range this.Fields {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Fields", err)
			}
		}
	}
	return nil
}
func (this *IndexField) Validate() error {
	return nil
}
func (this *ListView) Validate() error {
	for _, item := range this.Filters {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Filters", err)
			}
		}
	}
	if this.SharedTo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SharedTo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SharedTo", err)
		}
	}
	return nil
}
func (this *NamedFilter) Validate() error {
	for _, item := range this.FilterItems {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("FilterItems", err)
			}
		}
	}
	return nil
}
func (this *ProfileSearchLayouts) Validate() error {
	return nil
}
func (this *RecordType) Validate() error {
	for _, item := range this.PicklistValues {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("PicklistValues", err)
			}
		}
	}
	return nil
}
func (this *RecordTypePicklistValue) Validate() error {
	for _, item := range this.Values {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Values", err)
			}
		}
	}
	return nil
}
func (this *SearchLayouts) Validate() error {
	return nil
}
func (this *SharingReason) Validate() error {
	return nil
}
func (this *SharingRecalculation) Validate() error {
	return nil
}
func (this *ValidationRule) Validate() error {
	return nil
}
func (this *WebLink) Validate() error {
	return nil
}
func (this *PicklistValue) Validate() error {
	return nil
}
func (this *ListViewFilter) Validate() error {
	return nil
}
func (this *SharedTo) Validate() error {
	return nil
}
func (this *FilterItem) Validate() error {
	return nil
}
func (this *ValueSet) Validate() error {
	if this.ValueSetDefinition != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ValueSetDefinition); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ValueSetDefinition", err)
		}
	}
	if this.ValueSettings != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ValueSettings); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ValueSettings", err)
		}
	}
	return nil
}
func (this *ValueSetValuesDefinition) Validate() error {
	if this.Value != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Value); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Value", err)
		}
	}
	return nil
}
func (this *ValueSettings) Validate() error {
	return nil
}
func (this *CustomValue) Validate() error {
	return nil
}
