// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: index.proto

package index

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Document) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *FindDocumentRequest) Validate() error {
	return nil
}
func (this *DeleteDocumentRequest) Validate() error {
	return nil
}
