// Code generated by protoc-gen-go. DO NOT EDIT.
// source: index.proto

package index

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Document struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ObjId                string              `protobuf:"bytes,2,opt,name=objId,proto3" json:"objId,omitempty"`
	Fields               map[string]*any.Any `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{0}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Document) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

func (m *Document) GetFields() map[string]*any.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type FindDocumentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ObjId                string   `protobuf:"bytes,2,opt,name=objId,proto3" json:"objId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindDocumentRequest) Reset()         { *m = FindDocumentRequest{} }
func (m *FindDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*FindDocumentRequest) ProtoMessage()    {}
func (*FindDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{1}
}

func (m *FindDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindDocumentRequest.Unmarshal(m, b)
}
func (m *FindDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindDocumentRequest.Marshal(b, m, deterministic)
}
func (m *FindDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindDocumentRequest.Merge(m, src)
}
func (m *FindDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_FindDocumentRequest.Size(m)
}
func (m *FindDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindDocumentRequest proto.InternalMessageInfo

func (m *FindDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FindDocumentRequest) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

type DeleteDocumentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ObjId                string   `protobuf:"bytes,2,opt,name=objId,proto3" json:"objId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDocumentRequest) Reset()         { *m = DeleteDocumentRequest{} }
func (m *DeleteDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDocumentRequest) ProtoMessage()    {}
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{2}
}

func (m *DeleteDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDocumentRequest.Unmarshal(m, b)
}
func (m *DeleteDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDocumentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDocumentRequest.Merge(m, src)
}
func (m *DeleteDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDocumentRequest.Size(m)
}
func (m *DeleteDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDocumentRequest proto.InternalMessageInfo

func (m *DeleteDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteDocumentRequest) GetObjId() string {
	if m != nil {
		return m.ObjId
	}
	return ""
}

func init() {
	proto.RegisterType((*Document)(nil), "index.Document")
	proto.RegisterMapType((map[string]*any.Any)(nil), "index.Document.FieldsEntry")
	proto.RegisterType((*FindDocumentRequest)(nil), "index.FindDocumentRequest")
	proto.RegisterType((*DeleteDocumentRequest)(nil), "index.DeleteDocumentRequest")
}

func init() { proto.RegisterFile("index.proto", fileDescriptor_f750e0f7889345b5) }

var fileDescriptor_f750e0f7889345b5 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x50, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x6e, 0x52, 0x12, 0xea, 0x04, 0xac, 0xac, 0x15, 0x62, 0xf4, 0x50, 0x72, 0x2a, 0x22, 0x5b,
	0x48, 0x2f, 0xfe, 0xe0, 0x41, 0xad, 0x05, 0x4f, 0x42, 0xc4, 0x8b, 0xb7, 0xa4, 0x3b, 0x2d, 0xab,
	0x71, 0xb7, 0xa6, 0x9b, 0x60, 0x5e, 0xcc, 0x17, 0xf2, 0x45, 0xa4, 0xbb, 0x09, 0x48, 0xc9, 0xa1,
	0x78, 0xdb, 0xf9, 0x7e, 0xf6, 0x9b, 0x6f, 0xc0, 0xe3, 0x82, 0xe1, 0x17, 0x5d, 0xe5, 0x52, 0x49,
	0xe2, 0xe8, 0x21, 0x38, 0x5e, 0x4a, 0xb9, 0xcc, 0x70, 0xac, 0xc1, 0xb4, 0x58, 0x8c, 0x13, 0x51,
	0x19, 0x45, 0xf8, 0x6d, 0x41, 0x6f, 0x2a, 0xe7, 0xc5, 0x07, 0x0a, 0x45, 0xf6, 0xc1, 0xe6, 0xcc,
	0xb7, 0x86, 0xd6, 0x68, 0x2f, 0xb6, 0x39, 0x23, 0x03, 0x70, 0x64, 0xfa, 0xf6, 0xc8, 0x7c, 0x5b,
	0x43, 0x66, 0x20, 0x13, 0x70, 0x17, 0x1c, 0x33, 0xb6, 0xf6, 0xbb, 0xc3, 0xee, 0xc8, 0x8b, 0x4e,
	0xa8, 0x89, 0x6c, 0xbe, 0xa1, 0x33, 0xcd, 0x3e, 0x08, 0x95, 0x57, 0x71, 0x2d, 0x0d, 0x9e, 0xc0,
	0xfb, 0x03, 0x93, 0x03, 0xe8, 0xbe, 0x63, 0x55, 0x47, 0x6d, 0x9e, 0xe4, 0x0c, 0x9c, 0x32, 0xc9,
	0x0a, 0xd4, 0x59, 0x5e, 0x34, 0xa0, 0x66, 0x67, 0xda, 0xec, 0x4c, 0x6f, 0x45, 0x15, 0x1b, 0xc9,
	0x95, 0x7d, 0x61, 0x85, 0xd7, 0x70, 0x38, 0xe3, 0x82, 0x35, 0xa1, 0x31, 0x7e, 0x16, 0xb8, 0xde,
	0xb1, 0x42, 0x78, 0x03, 0x47, 0x53, 0xcc, 0x50, 0xe1, 0xbf, 0xec, 0xd1, 0x8f, 0x05, 0xfd, 0xc6,
	0xf9, 0x8c, 0x79, 0xc9, 0xe7, 0x48, 0xce, 0xc1, 0xbd, 0xcf, 0x31, 0x51, 0x48, 0xfa, 0x5b, 0xf7,
	0x08, 0xb6, 0x81, 0xb0, 0xb3, 0x51, 0xbf, 0xac, 0xd8, 0xae, 0xea, 0x4b, 0xe8, 0xc5, 0xa8, 0x72,
	0x8e, 0x25, 0x92, 0xa0, 0xa6, 0x5b, 0xca, 0xb7, 0x5b, 0x5d, 0xd3, 0x94, 0x9c, 0x36, 0x64, 0x5b,
	0xf1, 0x16, 0xeb, 0x9d, 0xfd, 0xda, 0x49, 0x5d, 0x7d, 0xfe, 0xc9, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x8f, 0x3e, 0xca, 0xe2, 0x56, 0x02, 0x00, 0x00,
}
