// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/data/data.proto

package data // import "github.com/objforce/objforce/proto/data"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import emptypb "google.golang.org/protobuf/types/known/emptypb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SObject struct {
	OrgId                string   `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	FieldsToNull         []string `protobuf:"bytes,3,rep,name=fieldsToNull,proto3" json:"fieldsToNull,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Fields               string   `protobuf:"bytes,5,opt,name=Fields,proto3" json:"Fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SObject) Reset()         { *m = SObject{} }
func (m *SObject) String() string { return proto.CompactTextString(m) }
func (*SObject) ProtoMessage()    {}
func (*SObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_e9f7bbc9105c583b, []int{0}
}
func (m *SObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SObject.Unmarshal(m, b)
}
func (m *SObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SObject.Marshal(b, m, deterministic)
}
func (dst *SObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SObject.Merge(dst, src)
}
func (m *SObject) XXX_Size() int {
	return xxx_messageInfo_SObject.Size(m)
}
func (m *SObject) XXX_DiscardUnknown() {
	xxx_messageInfo_SObject.DiscardUnknown(m)
}

var xxx_messageInfo_SObject proto.InternalMessageInfo

func (m *SObject) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *SObject) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SObject) GetFieldsToNull() []string {
	if m != nil {
		return m.FieldsToNull
	}
	return nil
}

func (m *SObject) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SObject) GetFields() string {
	if m != nil {
		return m.Fields
	}
	return ""
}

type CreateSObjectRequest struct {
	Object               *SObject `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSObjectRequest) Reset()         { *m = CreateSObjectRequest{} }
func (m *CreateSObjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSObjectRequest) ProtoMessage()    {}
func (*CreateSObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_e9f7bbc9105c583b, []int{1}
}
func (m *CreateSObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSObjectRequest.Unmarshal(m, b)
}
func (m *CreateSObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSObjectRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSObjectRequest.Merge(dst, src)
}
func (m *CreateSObjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSObjectRequest.Size(m)
}
func (m *CreateSObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSObjectRequest proto.InternalMessageInfo

func (m *CreateSObjectRequest) GetObject() *SObject {
	if m != nil {
		return m.Object
	}
	return nil
}

type UpdateSObjectRequest struct {
	Object               *SObject `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSObjectRequest) Reset()         { *m = UpdateSObjectRequest{} }
func (m *UpdateSObjectRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSObjectRequest) ProtoMessage()    {}
func (*UpdateSObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_e9f7bbc9105c583b, []int{2}
}
func (m *UpdateSObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSObjectRequest.Unmarshal(m, b)
}
func (m *UpdateSObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSObjectRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateSObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSObjectRequest.Merge(dst, src)
}
func (m *UpdateSObjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSObjectRequest.Size(m)
}
func (m *UpdateSObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSObjectRequest proto.InternalMessageInfo

func (m *UpdateSObjectRequest) GetObject() *SObject {
	if m != nil {
		return m.Object
	}
	return nil
}

type UpsertSObjectRequest struct {
	Object               *SObject `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertSObjectRequest) Reset()         { *m = UpsertSObjectRequest{} }
func (m *UpsertSObjectRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertSObjectRequest) ProtoMessage()    {}
func (*UpsertSObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_e9f7bbc9105c583b, []int{3}
}
func (m *UpsertSObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertSObjectRequest.Unmarshal(m, b)
}
func (m *UpsertSObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertSObjectRequest.Marshal(b, m, deterministic)
}
func (dst *UpsertSObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertSObjectRequest.Merge(dst, src)
}
func (m *UpsertSObjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertSObjectRequest.Size(m)
}
func (m *UpsertSObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertSObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertSObjectRequest proto.InternalMessageInfo

func (m *UpsertSObjectRequest) GetObject() *SObject {
	if m != nil {
		return m.Object
	}
	return nil
}

type UpsertSObjectResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Errors               []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertSObjectResponse) Reset()         { *m = UpsertSObjectResponse{} }
func (m *UpsertSObjectResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertSObjectResponse) ProtoMessage()    {}
func (*UpsertSObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_e9f7bbc9105c583b, []int{4}
}
func (m *UpsertSObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertSObjectResponse.Unmarshal(m, b)
}
func (m *UpsertSObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertSObjectResponse.Marshal(b, m, deterministic)
}
func (dst *UpsertSObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertSObjectResponse.Merge(dst, src)
}
func (m *UpsertSObjectResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertSObjectResponse.Size(m)
}
func (m *UpsertSObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertSObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertSObjectResponse proto.InternalMessageInfo

func (m *UpsertSObjectResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *UpsertSObjectResponse) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *UpsertSObjectResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpsertSObjectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetSObjectRequest struct {
	OrgId                string   `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Fields               []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSObjectRequest) Reset()         { *m = GetSObjectRequest{} }
func (m *GetSObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetSObjectRequest) ProtoMessage()    {}
func (*GetSObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_e9f7bbc9105c583b, []int{5}
}
func (m *GetSObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSObjectRequest.Unmarshal(m, b)
}
func (m *GetSObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSObjectRequest.Marshal(b, m, deterministic)
}
func (dst *GetSObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSObjectRequest.Merge(dst, src)
}
func (m *GetSObjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetSObjectRequest.Size(m)
}
func (m *GetSObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSObjectRequest proto.InternalMessageInfo

func (m *GetSObjectRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *GetSObjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetSObjectRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *GetSObjectRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type DeleteSObjectRequest struct {
	OrgId                string   `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSObjectRequest) Reset()         { *m = DeleteSObjectRequest{} }
func (m *DeleteSObjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSObjectRequest) ProtoMessage()    {}
func (*DeleteSObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_e9f7bbc9105c583b, []int{6}
}
func (m *DeleteSObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSObjectRequest.Unmarshal(m, b)
}
func (m *DeleteSObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSObjectRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteSObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSObjectRequest.Merge(dst, src)
}
func (m *DeleteSObjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSObjectRequest.Size(m)
}
func (m *DeleteSObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSObjectRequest proto.InternalMessageInfo

func (m *DeleteSObjectRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *DeleteSObjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteSObjectRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode           int32    `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_e9f7bbc9105c583b, []int{7}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*SObject)(nil), "data.SObject")
	proto.RegisterType((*CreateSObjectRequest)(nil), "data.CreateSObjectRequest")
	proto.RegisterType((*UpdateSObjectRequest)(nil), "data.UpdateSObjectRequest")
	proto.RegisterType((*UpsertSObjectRequest)(nil), "data.UpsertSObjectRequest")
	proto.RegisterType((*UpsertSObjectResponse)(nil), "data.UpsertSObjectResponse")
	proto.RegisterType((*GetSObjectRequest)(nil), "data.GetSObjectRequest")
	proto.RegisterType((*DeleteSObjectRequest)(nil), "data.DeleteSObjectRequest")
	proto.RegisterType((*Error)(nil), "data.Error")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SObjectServiceClient is the client API for SObjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SObjectServiceClient interface {
	Create(ctx context.Context, in *CreateSObjectRequest, opts ...grpc.CallOption) (*SObject, error)
	Update(ctx context.Context, in *UpdateSObjectRequest, opts ...grpc.CallOption) (*SObject, error)
	Upsert(ctx context.Context, in *UpsertSObjectRequest, opts ...grpc.CallOption) (*UpsertSObjectResponse, error)
	Get(ctx context.Context, in *GetSObjectRequest, opts ...grpc.CallOption) (*SObject, error)
	Delete(ctx context.Context, in *DeleteSObjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sObjectServiceClient struct {
	cc *grpc.ClientConn
}

func NewSObjectServiceClient(cc *grpc.ClientConn) SObjectServiceClient {
	return &sObjectServiceClient{cc}
}

func (c *sObjectServiceClient) Create(ctx context.Context, in *CreateSObjectRequest, opts ...grpc.CallOption) (*SObject, error) {
	out := new(SObject)
	err := c.cc.Invoke(ctx, "/data.SObjectService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sObjectServiceClient) Update(ctx context.Context, in *UpdateSObjectRequest, opts ...grpc.CallOption) (*SObject, error) {
	out := new(SObject)
	err := c.cc.Invoke(ctx, "/data.SObjectService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sObjectServiceClient) Upsert(ctx context.Context, in *UpsertSObjectRequest, opts ...grpc.CallOption) (*UpsertSObjectResponse, error) {
	out := new(UpsertSObjectResponse)
	err := c.cc.Invoke(ctx, "/data.SObjectService/Upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sObjectServiceClient) Get(ctx context.Context, in *GetSObjectRequest, opts ...grpc.CallOption) (*SObject, error) {
	out := new(SObject)
	err := c.cc.Invoke(ctx, "/data.SObjectService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sObjectServiceClient) Delete(ctx context.Context, in *DeleteSObjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/data.SObjectService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SObjectServiceServer is the server API for SObjectService service.
type SObjectServiceServer interface {
	Create(context.Context, *CreateSObjectRequest) (*SObject, error)
	Update(context.Context, *UpdateSObjectRequest) (*SObject, error)
	Upsert(context.Context, *UpsertSObjectRequest) (*UpsertSObjectResponse, error)
	Get(context.Context, *GetSObjectRequest) (*SObject, error)
	Delete(context.Context, *DeleteSObjectRequest) (*emptypb.Empty, error)
}

func RegisterSObjectServiceServer(s *grpc.Server, srv SObjectServiceServer) {
	s.RegisterService(&_SObjectService_serviceDesc, srv)
}

func _SObjectService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SObjectServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.SObjectService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SObjectServiceServer).Create(ctx, req.(*CreateSObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SObjectService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SObjectServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.SObjectService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SObjectServiceServer).Update(ctx, req.(*UpdateSObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SObjectService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertSObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SObjectServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.SObjectService/Upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SObjectServiceServer).Upsert(ctx, req.(*UpsertSObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SObjectService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SObjectServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.SObjectService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SObjectServiceServer).Get(ctx, req.(*GetSObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SObjectService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SObjectServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.SObjectService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SObjectServiceServer).Delete(ctx, req.(*DeleteSObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SObjectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "data.SObjectService",
	HandlerType: (*SObjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SObjectService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SObjectService_Update_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _SObjectService_Upsert_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SObjectService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SObjectService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/data/data.proto",
}

func init() { proto.RegisterFile("proto/data/data.proto", fileDescriptor_data_e9f7bbc9105c583b) }

var fileDescriptor_data_e9f7bbc9105c583b = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x4d, 0xec, 0xc4, 0x69, 0x27, 0x50, 0x89, 0x55, 0x5a, 0x2c, 0x57, 0x42, 0x91, 0x11, 0x52,
	0x0e, 0xc8, 0x96, 0x82, 0x38, 0x21, 0x90, 0x20, 0x94, 0x8a, 0x0b, 0x20, 0x17, 0x2e, 0xdc, 0xfc,
	0x31, 0x31, 0xae, 0x1c, 0xd6, 0xec, 0xae, 0x91, 0x7a, 0x82, 0x1f, 0xc5, 0x0f, 0x44, 0xfb, 0x55,
	0xa7, 0xb5, 0x0f, 0x88, 0x5e, 0xac, 0x9d, 0xb7, 0xfb, 0x66, 0x67, 0xe6, 0xbd, 0x35, 0x1c, 0x37,
	0x8c, 0x0a, 0x1a, 0x17, 0xa9, 0x48, 0xd5, 0x27, 0x52, 0x31, 0x99, 0xc8, 0x75, 0x70, 0x5a, 0x52,
	0x5a, 0xd6, 0x18, 0x2b, 0x2c, 0x6b, 0xb7, 0x31, 0xee, 0x1a, 0x71, 0xa5, 0x8f, 0x84, 0xbf, 0x60,
	0x76, 0xf1, 0x31, 0xbb, 0xc4, 0x5c, 0x90, 0x05, 0x4c, 0x29, 0x2b, 0xdf, 0x17, 0xfe, 0x78, 0x39,
	0x5e, 0x1d, 0x26, 0x3a, 0x20, 0x04, 0x26, 0xe2, 0xaa, 0x41, 0xdf, 0x51, 0xa0, 0x5a, 0x93, 0x10,
	0xee, 0x6d, 0x2b, 0xac, 0x0b, 0xfe, 0x99, 0x7e, 0x68, 0xeb, 0xda, 0x77, 0x97, 0xee, 0xea, 0x30,
	0xb9, 0x81, 0x91, 0x23, 0x70, 0xaa, 0xc2, 0x9f, 0x28, 0x96, 0x53, 0x15, 0xe4, 0x04, 0xbc, 0x77,
	0x6a, 0xdf, 0x9f, 0x2a, 0xcc, 0x44, 0xe1, 0x4b, 0x58, 0x6c, 0x18, 0xa6, 0x02, 0x4d, 0x19, 0x09,
	0xfe, 0x68, 0x91, 0x0b, 0xf2, 0x04, 0x3c, 0xaa, 0x00, 0x55, 0xce, 0x7c, 0x7d, 0x3f, 0x52, 0x8d,
	0xd9, 0x53, 0x66, 0x53, 0xd2, 0xbf, 0x34, 0xc5, 0xdd, 0xe8, 0x1c, 0x99, 0xf8, 0x3f, 0xfa, 0xef,
	0x31, 0x1c, 0xdf, 0xe2, 0xf3, 0x86, 0x7e, 0xe7, 0x48, 0x7c, 0x98, 0xe5, 0xaa, 0x2d, 0x3d, 0xce,
	0x83, 0xc4, 0x86, 0xe4, 0x31, 0x78, 0xc8, 0x18, 0x65, 0xdc, 0x77, 0x96, 0xee, 0x6a, 0xbe, 0x9e,
	0xeb, 0xd4, 0x67, 0x12, 0x4b, 0xcc, 0x96, 0x99, 0x9e, 0x7b, 0x3d, 0x3d, 0x1f, 0x66, 0xbc, 0xcd,
	0x73, 0xe4, 0x5c, 0x8d, 0xf4, 0x20, 0xb1, 0x61, 0x88, 0xf0, 0xe0, 0x1c, 0x6f, 0x97, 0x3f, 0x2c,
	0xa5, 0x4e, 0xea, 0xec, 0x4b, 0xa2, 0x25, 0x33, 0x02, 0x9a, 0xe8, 0x5a, 0xf2, 0x49, 0x27, 0x79,
	0xf8, 0x09, 0x16, 0x6f, 0xb1, 0xc6, 0xde, 0x9c, 0xff, 0xed, 0x26, 0x9b, 0xd1, 0xdd, 0xcb, 0xf8,
	0x1a, 0xa6, 0xaa, 0x67, 0xd9, 0xdb, 0x0e, 0x39, 0x4f, 0x4b, 0x34, 0x49, 0x6c, 0x48, 0x1e, 0x01,
	0x70, 0x91, 0x8a, 0x96, 0x6f, 0x68, 0xa1, 0x1d, 0x38, 0x4d, 0xf6, 0x90, 0xf5, 0x1f, 0x07, 0x8e,
	0x4c, 0x3d, 0x17, 0xc8, 0x7e, 0x56, 0x39, 0x92, 0xe7, 0xe0, 0x69, 0x3b, 0x91, 0x40, 0xcf, 0x75,
	0xc8, 0x5c, 0xc1, 0x4d, 0x39, 0xc3, 0x91, 0xa4, 0x69, 0x1b, 0x59, 0xda, 0x90, 0xa9, 0xfa, 0xb4,
	0x8d, 0xa4, 0x49, 0xf9, 0x3b, 0x5a, 0xdf, 0x4c, 0xc1, 0xe9, 0xe0, 0x9e, 0x36, 0x4a, 0x38, 0x22,
	0x31, 0xb8, 0xe7, 0x28, 0xc8, 0x43, 0x7d, 0xaa, 0x27, 0x66, 0xff, 0xd6, 0x57, 0xe0, 0x69, 0x2d,
	0xec, 0xad, 0x43, 0xca, 0x04, 0x27, 0x91, 0x7e, 0xf7, 0x91, 0x7d, 0xf7, 0xd1, 0x99, 0x7c, 0xf7,
	0xe1, 0xe8, 0x4d, 0xf4, 0xf5, 0x69, 0x59, 0x89, 0x6f, 0x6d, 0x16, 0xe5, 0x74, 0x17, 0xd3, 0xec,
	0x72, 0x4b, 0x59, 0x8e, 0xdd, 0xa2, 0xfb, 0x99, 0xbc, 0x90, 0x9f, 0xcc, 0x53, 0xc0, 0xb3, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x08, 0x70, 0xb6, 0x15, 0x66, 0x04, 0x00, 0x00,
}
